<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_66436fb1b4f7f',
    'title' => __('Audience', 'api-event-manager'),
    'fields' => array(
        0 => array(
            'key' => 'field_65a52a6374b0c',
            'label' => __('Audience', 'api-event-manager'),
            'name' => 'audience',
            'aria-label' => '',
            'type' => 'checkbox',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 0,
            'choices' => array(
                370 => __('Audience A', 'api-event-manager'),
                371 => __('Audience B', 'api-event-manager'),
                372 => __('Audience C', 'api-event-manager'),
                373 => __('Audience D', 'api-event-manager'),
            ),
            'default_value' => array(
            ),
            'return_format' => 'value',
            'allow_custom' => 0,
            'layout' => 'horizontal',
            'toggle' => 0,
            'save_custom' => 0,
            'custom_choice_button_text' => 'Add new choice',
        ),
        1 => array(
            'key' => 'field_6650a5cb1d933',
            'label' => __('Age restriction', 'api-event-manager'),
            'name' => 'age_restriction',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 0,
            'message' => '',
            'default_value' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'ui' => 1,
        ),
        2 => array(
            'key' => 'field_6650a5e41d934',
            'label' => __('Age Restriction Info', 'api-event-manager'),
            'name' => 'age_restriction_info',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_6650a5cb1d933',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 0,
            'default_value' => '',
            'maxlength' => 250,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        3 => array(
            'key' => 'field_6650a92febecf',
            'label' => __('Cognitive Accessibility', 'api-event-manager'),
            'name' => 'cognitive_accessibility',
            'aria-label' => '',
            'type' => 'acfe_taxonomy_terms',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 0,
            'taxonomy' => array(
                0 => 'cognitive-accessibility',
            ),
            'allow_terms' => '',
            'allow_level' => '',
            'field_type' => 'checkbox',
            'default_value' => array(
            ),
            'return_format' => 'id',
            'layout' => 'vertical',
            'toggle' => 0,
            'save_terms' => 1,
            'load_terms' => 1,
            'choices' => array(
            ),
            'ui' => 0,
            'multiple' => 0,
            'allow_null' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'search_placeholder' => '',
            'allow_custom' => 0,
            'other_choice' => 0,
        ),
        4 => array(
            'key' => 'field_66604749d8dfa',
            'label' => __('Physical Accessibility', 'api-event-manager'),
            'name' => 'physical_accessibility',
            'aria-label' => '',
            'type' => 'acfe_taxonomy_terms',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 0,
            'taxonomy' => array(
                0 => 'physical-accessibility',
            ),
            'allow_terms' => '',
            'allow_level' => '',
            'field_type' => 'checkbox',
            'default_value' => array(
            ),
            'return_format' => 'id',
            'layout' => 'vertical',
            'toggle' => 0,
            'save_terms' => 1,
            'load_terms' => 1,
            'choices' => array(
            ),
            'ui' => 0,
            'multiple' => 0,
            'allow_null' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'search_placeholder' => '',
            'allow_custom' => 0,
            'other_choice' => 0,
        ),
        5 => array(
            'key' => 'field_66604764d8dfb',
            'label' => __('Amenities', 'api-event-manager'),
            'name' => 'amenities',
            'aria-label' => '',
            'type' => 'acfe_taxonomy_terms',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 0,
            'taxonomy' => array(
                0 => 'amenities',
            ),
            'allow_terms' => '',
            'allow_level' => '',
            'field_type' => 'checkbox',
            'default_value' => array(
            ),
            'return_format' => 'id',
            'layout' => 'vertical',
            'toggle' => 0,
            'save_terms' => 1,
            'load_terms' => 1,
            'choices' => array(
            ),
            'ui' => 0,
            'multiple' => 0,
            'allow_null' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'search_placeholder' => '',
            'allow_custom' => 0,
            'other_choice' => 0,
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'event',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'left',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
));
}