<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_66436bf782af1',
    'title' => __('Description', 'api-event-manager'),
    'fields' => array(
        0 => array(
            'key' => 'field_66106dc161830',
            'label' => __('Image', 'api-event-manager'),
            'name' => '_thumbnail_id',
            'aria-label' => '',
            'type' => 'image',
            'instructions' => __('Enhance your event by including a high-resolution image in <strong>JPG format</strong>. As the initial point of contact, the image plays a pivotal role in capturing users\' attention, making it essential for attracting attendees.', 'api-event-manager'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 1,
            'return_format' => 'array',
            'library' => 'uploadedTo',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => 'jpg, jpeg',
            'preview_size' => 'medium',
            'uploader' => '',
            'acfe_thumbnail' => 0,
        ),
        1 => array(
            'key' => 'field_65a6206610d45',
            'label' => __('Short description', 'api-event-manager'),
            'name' => 'description',
            'aria-label' => '',
            'type' => 'textarea',
            'instructions' => __('Enter a brief, enticing description of your event. Make it irresistible - an event not to be missed!', 'api-event-manager'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'rows' => '',
            'placeholder' => '',
            'new_lines' => '',
            'acfe_textarea_code' => 0,
        ),
        2 => array(
            'key' => 'field_65a115151a872',
            'label' => __('About', 'api-event-manager'),
            'name' => 'about',
            'aria-label' => '',
            'type' => 'textarea',
            'instructions' => __('Provide essential information about your event, including featured speakers or performers, activities, and any other pertinent details.', 'api-event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'rows' => 12,
            'placeholder' => '',
            'new_lines' => '',
            'acfe_textarea_code' => 0,
        ),
        3 => array(
            'key' => 'field_65f14f7826756',
            'label' => __('Accessability information', 'api-event-manager'),
            'name' => 'accessabilityInformation',
            'aria-label' => '',
            'type' => 'textarea',
            'instructions' => __('Include details on event accessibility for all attendees, covering wheelchair access, parking, elevators, sign language interpreters, and other accommodations.', 'api-event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'rows' => '',
            'placeholder' => '',
            'new_lines' => '',
            'acfe_textarea_code' => 0,
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'event',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'left',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
));
}