<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_57610ebadcee8',
    'title' => __('Event', 'event-manager'),
    'fields' => array(
        0 => array(
            'key' => 'field_5761103c83966',
            'label' => __('Event', 'event-manager'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        1 => array(
            'key' => 'field_5761144d641f2',
            'label' => __('Website', 'event-manager'),
            'name' => 'event_link',
            'type' => 'url',
            'instructions' => __('Link to event website.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
        ),
        2 => array(
            'key' => 'field_57c7fbbee9d7b',
            'label' => __('Additional links', 'event-manager'),
            'name' => 'additional_links',
            'type' => 'repeater',
            'instructions' => __('Additional links to websites.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'block',
            'button_label' => __('Add link', 'event-manager'),
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_57c7fd2381ffb',
                    'label' => __('Link', 'event-manager'),
                    'name' => 'link',
                    'type' => 'url',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                ),
            ),
        ),
        3 => array(
            'key' => 'field_57c97ba976b20',
            'label' => __('Related events', 'event-manager'),
            'name' => 'related_events',
            'type' => 'post_object',
            'instructions' => __('Links to other events associated with this event.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'post_type' => array(
                0 => 'event',
            ),
            'taxonomy' => array(
            ),
            'allow_null' => 0,
            'multiple' => 1,
            'return_format' => 'object',
            'ui' => 1,
        ),
        4 => array(
            'key' => 'field_57d274173bf4c',
            'label' => __('Occasions', 'event-manager'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        5 => array(
            'key' => 'field_57d8f238dd06b',
            'label' => __('Event occasions', 'event-manager'),
            'name' => '',
            'type' => 'message',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => __('Add occasions to this event. Does the event occur each week? Then add a rule for recurring events.', 'event-manager'),
            'new_lines' => 'wpautop',
            'esc_html' => 0,
        ),
        6 => array(
            'key' => 'field_5761106783967',
            'label' => __('Date', 'event-manager'),
            'name' => 'occasions',
            'type' => 'repeater',
            'instructions' => __('Start and end time of the event.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'block',
            'button_label' => __('Add occasion', 'event-manager'),
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_5761164591649',
                    'label' => __('Status', 'event-manager'),
                    'name' => 'status',
                    'type' => 'radio',
                    'instructions' => __('Select if event is on schedule or not.', 'event-manager'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'scheduled' => __('Scheduled', 'event-manager'),
                        'rescheduled' => __('Rescheduled', 'event-manager'),
                        'cancelled' => __('Cancelled', 'event-manager'),
                    ),
                    'allow_null' => 0,
                    'other_choice' => 0,
                    'save_other_choice' => 0,
                    'default_value' => 'scheduled',
                    'layout' => 'horizontal',
                    'return_format' => 'value',
                ),
                1 => array(
                    'key' => 'field_57f3c0670c4a9',
                    'label' => __('Exeption information', 'event-manager'),
                    'name' => 'occ_exeption_information',
                    'type' => 'text',
                    'instructions' => __('Information about why there have been an exception.', 'event-manager'),
                    'required' => 0,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_5761164591649',
                                'operator' => '!=',
                                'value' => 'scheduled',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                2 => array(
                    'key' => 'field_5761109a83968',
                    'label' => __('Start date', 'event-manager'),
                    'name' => 'start_date',
                    'type' => 'date_time_picker',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33',
                        'class' => 'start_date',
                        'id' => 'start_date_id',
                    ),
                    'display_format' => 'Y-m-d H:i',
                    'return_format' => 'Y-m-d H:i',
                    'first_day' => 1,
                ),
                3 => array(
                    'key' => 'field_576110e583969',
                    'label' => __('End date', 'event-manager'),
                    'name' => 'end_date',
                    'type' => 'date_time_picker',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33',
                        'class' => 'end_date',
                        'id' => 'end_date_id',
                    ),
                    'display_format' => 'Y-m-d H:i',
                    'return_format' => 'Y-m-d H:i',
                    'first_day' => 1,
                ),
                4 => array(
                    'key' => 'field_5761169e07309',
                    'label' => __('Door time', 'event-manager'),
                    'name' => 'door_time',
                    'type' => 'date_time_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33',
                        'class' => 'door_time',
                        'id' => 'door_time_id',
                    ),
                    'display_format' => 'Y-m-d H:i',
                    'return_format' => 'Y-m-d H:i',
                    'first_day' => 1,
                ),
                5 => array(
                    'key' => 'field_57611277ef032',
                    'label' => __('Override content', 'event-manager'),
                    'name' => 'content_mode',
                    'type' => 'radio',
                    'instructions' => __('Use master or custom content for this occasion.', 'event-manager'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'master' => __('Use master content', 'event-manager'),
                        'custom' => __('Use custom content', 'event-manager'),
                    ),
                    'allow_null' => 0,
                    'other_choice' => 0,
                    'save_other_choice' => 0,
                    'default_value' => '',
                    'layout' => 'horizontal',
                    'return_format' => 'value',
                ),
                6 => array(
                    'key' => 'field_576110fb8396a',
                    'label' => __('Content', 'event-manager'),
                    'name' => 'content',
                    'type' => 'wysiwyg',
                    'instructions' => __('Override the post content of the event.', 'event-manager'),
                    'required' => 1,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_57611277ef032',
                                'operator' => '==',
                                'value' => 'custom',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                    'delay' => 0,
                ),
                7 => array(
                    'key' => 'field_5ce6a8043b8e9',
                    'label' => __('Override location', 'event-manager'),
                    'name' => 'location_mode',
                    'type' => 'radio',
                    'instructions' => __('Use master or custom location for this occasion.', 'event-manager'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'master' => __('Use master location', 'event-manager'),
                        'custom' => __('Use custom location', 'event-manager'),
                    ),
                    'allow_null' => 0,
                    'other_choice' => 0,
                    'default_value' => '',
                    'layout' => 'horizontal',
                    'return_format' => 'value',
                    'save_other_choice' => 0,
                ),
                8 => array(
                    'key' => 'field_5ce6a39f92cb8',
                    'label' => __('Location', 'event-manager'),
                    'name' => 'location',
                    'type' => 'post_object',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_5ce6a8043b8e9',
                                'operator' => '==',
                                'value' => 'custom',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => array(
                        0 => 'location',
                    ),
                    'taxonomy' => '',
                    'allow_null' => 1,
                    'multiple' => 0,
                    'return_format' => 'id',
                    'ui' => 1,
                ),
            ),
        ),
        7 => array(
            'key' => 'field_57d2749e3bf4d',
            'label' => __('Recurrence rules', 'event-manager'),
            'name' => 'rcr_rules',
            'type' => 'repeater',
            'instructions' => __('Weekly recurring event.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => 'rcr_rules',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'row',
            'button_label' => __('Add rule', 'event-manager'),
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_57d275713bf4e',
                    'label' => __('Weekday', 'event-manager'),
                    'name' => 'rcr_week_day',
                    'type' => 'select',
                    'instructions' => __('The event will occur on this weekday', 'event-manager'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => 'rcr_day',
                        'id' => '',
                    ),
                    'choices' => array(
                        'Monday' => __('Monday', 'event-manager'),
                        'Tuesday' => __('Tuesday', 'event-manager'),
                        'Wednesday' => __('Wednesday', 'event-manager'),
                        'Thursday' => __('Thursday', 'event-manager'),
                        'Friday' => __('Friday', 'event-manager'),
                        'Saturday' => __('Saturday', 'event-manager'),
                        'Sunday' => __('Sunday', 'event-manager'),
                    ),
                    'default_value' => array(
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                ),
                1 => array(
                    'key' => 'field_5b0d3c9bef44f',
                    'label' => __('Weekly interval', 'event-manager'),
                    'name' => 'rcr_weekly_interval',
                    'type' => 'number',
                    'instructions' => __('Enter the weekly interval when the event occurs. 1 equals every week.', 'event-manager'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 1,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => 1,
                    'max' => 52,
                    'step' => 1,
                ),
                2 => array(
                    'key' => 'field_57d277153bf4f',
                    'label' => __('Start time', 'event-manager'),
                    'name' => 'rcr_start_time',
                    'type' => 'time_picker',
                    'instructions' => __('Start time of the event', 'event-manager'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i',
                    'return_format' => 'H:i',
                ),
                3 => array(
                    'key' => 'field_57d2777b3bf50',
                    'label' => __('End time', 'event-manager'),
                    'name' => 'rcr_end_time',
                    'type' => 'time_picker',
                    'instructions' => __('End time of the event', 'event-manager'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i',
                    'return_format' => 'H:i',
                ),
                4 => array(
                    'key' => 'field_57d6720f72407',
                    'label' => __('Door time', 'event-manager'),
                    'name' => 'rcr_door_time',
                    'type' => 'time_picker',
                    'instructions' => __('Door time of the event', 'event-manager'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i',
                    'return_format' => 'H:i',
                ),
                5 => array(
                    'key' => 'field_57d660a687234',
                    'label' => __('Start date', 'event-manager'),
                    'name' => 'rcr_start_date',
                    'type' => 'date_picker',
                    'instructions' => __('When the recurring event period starts.', 'event-manager'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => 'rcr_start_date',
                        'id' => '',
                    ),
                    'display_format' => 'Y-m-d',
                    'return_format' => 'Y-m-d',
                    'first_day' => 1,
                ),
                6 => array(
                    'key' => 'field_57d2787b3bf51',
                    'label' => __('End date', 'event-manager'),
                    'name' => 'rcr_end_date',
                    'type' => 'date_picker',
                    'instructions' => __('When the reccurring event period ends', 'event-manager'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => 'rcr_end_date',
                        'id' => '',
                    ),
                    'display_format' => 'Y-m-d',
                    'return_format' => 'Y-m-d',
                    'first_day' => 1,
                ),
                7 => array(
                    'key' => 'field_57d279addb0cb',
                    'label' => __('Exceptions', 'event-manager'),
                    'name' => 'rcr_exceptions',
                    'type' => 'repeater',
                    'instructions' => __('Add exceptions to this scheme.', 'event-manager'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => 'rcr_rules_exc',
                        'id' => '',
                    ),
                    'collapsed' => '',
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'block',
                    'button_label' => __('Add exception', 'event-manager'),
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_57d279f8db0cc',
                            'label' => __('Exception date', 'event-manager'),
                            'name' => 'rcr_exc_date',
                            'type' => 'date_picker',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => 'rcr_exc_date',
                                'id' => '',
                            ),
                            'display_format' => 'Y-m-d',
                            'return_format' => 'Y-m-d',
                            'first_day' => 1,
                        ),
                        1 => array(
                            'key' => 'field_57f3bb9c82f5e',
                            'label' => __('Status', 'event-manager'),
                            'name' => 'status_rcr_exc',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'default' => __('Default', 'event-manager'),
                                'rescheduled' => __('Rescheduled', 'event-manager'),
                                'cancelled' => __('Cancelled', 'event-manager'),
                            ),
                            'allow_null' => 0,
                            'other_choice' => 0,
                            'save_other_choice' => 0,
                            'default_value' => 'scheduled',
                            'layout' => 'horizontal',
                            'return_format' => 'value',
                        ),
                        2 => array(
                            'key' => 'field_57f3becaf31a5',
                            'label' => __('Exeption information', 'event-manager'),
                            'name' => 'rcr_exception_info',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_57f3bb9c82f5e',
                                        'operator' => '!=',
                                        'value' => 'default',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                    ),
                ),
            ),
        ),
        8 => array(
            'key' => 'field_576117b523a51',
            'label' => __('Location', 'event-manager'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        9 => array(
            'key' => 'field_576117c423a52',
            'label' => __('Location', 'event-manager'),
            'name' => 'location',
            'type' => 'post_object',
            'instructions' => __('Location or address for the event.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '45',
                'class' => '',
                'id' => '',
            ),
            'post_type' => array(
                0 => 'location',
            ),
            'taxonomy' => array(
            ),
            'allow_null' => 1,
            'multiple' => 0,
            'return_format' => 'id',
            'ui' => 1,
        ),
        10 => array(
            'key' => 'field_57ee2a23bd0b5',
            'label' => __('Additional locations', 'event-manager'),
            'name' => 'additional_locations',
            'type' => 'post_object',
            'instructions' => __('Add additional locations if the event takes place on more than one address.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'post_type' => array(
                0 => 'location',
            ),
            'taxonomy' => array(
            ),
            'allow_null' => 0,
            'multiple' => 1,
            'return_format' => 'id',
            'ui' => 1,
        ),
        11 => array(
            'key' => 'field_5c58562a86ddf',
            'label' => __('Accessibility', 'event-manager'),
            'name' => 'accessibility',
            'type' => 'checkbox',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'accessible_toilet' => __('Accessible toilet', 'event-manager'),
                'elevator_ ramp' => __('Elevator/ramp', 'event-manager'),
            ),
            'allow_custom' => 0,
            'default_value' => array(
            ),
            'layout' => 'vertical',
            'toggle' => 0,
            'return_format' => 'label',
            'save_custom' => 0,
        ),
        12 => array(
            'key' => 'field_57611356d9415',
            'label' => __('Organizer', 'event-manager'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        13 => array(
            'key' => 'field_5922a161ab32f',
            'label' => __('Organizers', 'event-manager'),
            'name' => 'organizers',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => 'field_5922a161ab331',
            'min' => 0,
            'max' => 0,
            'layout' => 'block',
            'button_label' => __('Add organizer', 'event-manager'),
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_5922a161ab330',
                    'label' => __('Main organizer', 'event-manager'),
                    'name' => 'main_organizer',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => __('Check the box if this is the main organizer for the event.', 'event-manager'),
                    'default_value' => 0,
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                ),
                1 => array(
                    'key' => 'field_5922a161ab331',
                    'label' => __('Organizer', 'event-manager'),
                    'name' => 'organizer',
                    'type' => 'post_object',
                    'instructions' => __('Select the company, organization or person that organizes the event.', 'event-manager'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => array(
                        0 => 'organizer',
                    ),
                    'taxonomy' => array(
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'return_format' => 'id',
                    'ui' => 1,
                ),
            ),
        ),
        14 => array(
            'key' => 'field_57a9d5f3804e1',
            'label' => __('Sponsors', 'event-manager'),
            'name' => 'supporters',
            'type' => 'post_object',
            'instructions' => __('Add sponsors to the event.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'post_type' => array(
                0 => 'sponsor',
            ),
            'taxonomy' => array(
            ),
            'allow_null' => 0,
            'multiple' => 1,
            'return_format' => 'object',
            'ui' => 1,
        ),
        15 => array(
            'key' => 'field_57611b73acf19',
            'label' => __('Booking & tickets', 'event-manager'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        16 => array(
            'key' => 'field_57611b82acf1a',
            'label' => __('Booking link', 'event-manager'),
            'name' => 'booking_link',
            'type' => 'url',
            'instructions' => __('External link to booking website.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
        ),
        17 => array(
            'key' => 'field_57611bffacf1d',
            'label' => __('Booking phone', 'event-manager'),
            'name' => 'booking_phone',
            'type' => 'text',
            'instructions' => __('Phone number to make bookings.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        18 => array(
            'key' => 'field_5b03ca36cd822',
            'label' => __('Email', 'event-manager'),
            'name' => 'booking_email',
            'type' => 'email',
            'instructions' => __('Email to make bookings.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        19 => array(
            'key' => 'field_5ae2d2fe2f26e',
            'label' => __('Ticket release date', 'event-manager'),
            'name' => 'ticket_release_date',
            'type' => 'date_time_picker',
            'instructions' => __('Date when the tickets is released.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'display_format' => 'Y-m-d H:i',
            'return_format' => 'Y-m-d H:i',
            'first_day' => 1,
        ),
        20 => array(
            'key' => 'field_57611befacf1c',
            'label' => __('Minimum age to attend the event', 'event-manager'),
            'name' => 'age_restriction',
            'type' => 'number',
            'instructions' => __('Enter age if this event is age restricted.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => __('e.g. 15', 'event-manager'),
            'prepend' => '',
            'append' => __('year', 'event-manager'),
            'min' => 0,
            'max' => '',
            'step' => '',
        ),
        21 => array(
            'key' => 'field_5ae2d0ba2f26c',
            'label' => __('Ticket stock', 'event-manager'),
            'name' => 'ticket_stock',
            'type' => 'number',
            'instructions' => __('Total amount of tickets.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => '',
            'max' => '',
            'step' => '',
        ),
        22 => array(
            'key' => 'field_5ae2d7f3916d3',
            'label' => __('Tickets remaining', 'event-manager'),
            'name' => 'tickets_remaining',
            'type' => 'number',
            'instructions' => __('Remaining amount of tickets for sale.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => '',
            'max' => '',
            'step' => '',
        ),
        23 => array(
            'key' => 'field_5ae320279d7e0',
            'label' => __('Additional ticket retailers', 'event-manager'),
            'name' => 'additional_ticket_retailers',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'block',
            'button_label' => __('Add', 'event-manager'),
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_5ae322b4caede',
                    'label' => __('Retailer', 'event-manager'),
                    'name' => 'retailer_name',
                    'type' => 'text',
                    'instructions' => __('Name of the retailer.', 'event-manager'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                1 => array(
                    'key' => 'field_5ae3251dcb3b0',
                    'label' => __('Ticket purchase URL', 'event-manager'),
                    'name' => 'booking_url',
                    'type' => 'url',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                ),
                2 => array(
                    'key' => 'field_5ae3213f9d7e3',
                    'label' => __('Ticket release date', 'event-manager'),
                    'name' => 'ticket_release_date',
                    'type' => 'date_time_picker',
                    'instructions' => __('Date when the tickets is released.', 'event-manager'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'Y-m-d H:i',
                    'return_format' => 'Y-m-d H:i',
                    'first_day' => 1,
                ),
                3 => array(
                    'key' => 'field_5ae321bd9d7e4',
                    'label' => __('Ticket stop date', 'event-manager'),
                    'name' => 'ticket_stop_date',
                    'type' => 'date_time_picker',
                    'instructions' => __('Date when the retailer stops selling tickets.', 'event-manager'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'Y-m-d H:i',
                    'return_format' => 'Y-m-d H:i',
                    'first_day' => 1,
                ),
            ),
        ),
        24 => array(
            'key' => 'field_57c7ed92054e6',
            'label' => __('Included in membership cards', 'event-manager'),
            'name' => 'membership_cards',
            'type' => 'post_object',
            'instructions' => __('Add membership cards where this event is included.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'post_type' => array(
                0 => 'membership-card',
            ),
            'taxonomy' => array(
            ),
            'allow_null' => 0,
            'multiple' => 1,
            'return_format' => 'object',
            'ui' => 1,
        ),
        25 => array(
            'key' => 'field_5afc2082b3eed',
            'label' => __('Entrance and ticket prices', 'event-manager'),
            'name' => '',
            'type' => 'message',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => __('Enter entrance and ticket prices for the event. Enter "0" if the event is free.', 'event-manager'),
            'new_lines' => 'wpautop',
            'esc_html' => 0,
        ),
        26 => array(
            'key' => 'field_57611c0cacf1e',
            'label' => __('Default price / Adult', 'event-manager'),
            'name' => 'price_adult',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => __('SEK', 'event-manager'),
            'maxlength' => '',
        ),
        27 => array(
            'key' => 'field_57b6fe18e65c4',
            'label' => __('Price student', 'event-manager'),
            'name' => 'price_student',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => __('SEK', 'event-manager'),
            'maxlength' => '',
        ),
        28 => array(
            'key' => 'field_57611c23acf1f',
            'label' => __('Price children', 'event-manager'),
            'name' => 'price_children',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => __('SEK', 'event-manager'),
            'maxlength' => '',
        ),
        29 => array(
            'key' => 'field_57f4fe8866a2d',
            'label' => __('Age restriction for children price', 'event-manager'),
            'name' => 'children_age',
            'type' => 'select',
            'instructions' => __('Children price is valid up to this age.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                0 => __('0', 'event-manager'),
                1 => __('1', 'event-manager'),
                2 => __('2', 'event-manager'),
                3 => __('3', 'event-manager'),
                4 => __('4', 'event-manager'),
                5 => __('5', 'event-manager'),
                6 => __('6', 'event-manager'),
                7 => __('7', 'event-manager'),
                8 => __('8', 'event-manager'),
                9 => __('9', 'event-manager'),
                10 => __('10', 'event-manager'),
                11 => __('11', 'event-manager'),
                12 => __('12', 'event-manager'),
                13 => __('13', 'event-manager'),
                14 => __('14', 'event-manager'),
                15 => __('15', 'event-manager'),
                16 => __('16', 'event-manager'),
                17 => __('17', 'event-manager'),
                18 => __('18', 'event-manager'),
                19 => __('19', 'event-manager'),
                20 => __('20', 'event-manager'),
                21 => __('21', 'event-manager'),
                22 => __('22', 'event-manager'),
                23 => __('23', 'event-manager'),
                24 => __('24', 'event-manager'),
                25 => __('25', 'event-manager'),
            ),
            'default_value' => array(
            ),
            'allow_null' => 1,
            'multiple' => 0,
            'ui' => 0,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '',
        ),
        30 => array(
            'key' => 'field_57b6fe5ee65c5',
            'label' => __('Price senior', 'event-manager'),
            'name' => 'price_senior',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => __('SEK', 'event-manager'),
            'maxlength' => '',
        ),
        31 => array(
            'key' => 'field_57f4fbaa4365e',
            'label' => __('Age restriction for senior price', 'event-manager'),
            'name' => 'senior_age',
            'type' => 'select',
            'instructions' => __('Senior price is valid from this age.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                50 => __('50', 'event-manager'),
                51 => __('51', 'event-manager'),
                52 => __('52', 'event-manager'),
                53 => __('53', 'event-manager'),
                54 => __('54', 'event-manager'),
                55 => __('55', 'event-manager'),
                56 => __('56', 'event-manager'),
                57 => __('57', 'event-manager'),
                58 => __('58', 'event-manager'),
                59 => __('59', 'event-manager'),
                60 => __('60', 'event-manager'),
                61 => __('61', 'event-manager'),
                62 => __('62', 'event-manager'),
                63 => __('63', 'event-manager'),
                64 => __('64', 'event-manager'),
                65 => __('65', 'event-manager'),
                66 => __('66', 'event-manager'),
                67 => __('67', 'event-manager'),
                68 => __('68', 'event-manager'),
                69 => __('69', 'event-manager'),
                70 => __('70', 'event-manager'),
                71 => __('71', 'event-manager'),
                72 => __('72', 'event-manager'),
                73 => __('73', 'event-manager'),
                74 => __('74', 'event-manager'),
                75 => __('75', 'event-manager'),
                76 => __('76', 'event-manager'),
                77 => __('77', 'event-manager'),
                78 => __('78', 'event-manager'),
                79 => __('79', 'event-manager'),
                80 => __('80', 'event-manager'),
                81 => __('81', 'event-manager'),
                82 => __('82', 'event-manager'),
                83 => __('83', 'event-manager'),
                84 => __('84', 'event-manager'),
                85 => __('85', 'event-manager'),
            ),
            'default_value' => array(
            ),
            'allow_null' => 1,
            'multiple' => 0,
            'ui' => 0,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '',
        ),
        32 => array(
            'key' => 'field_5ae2e55f94974',
            'label' => __('Additional ticket types', 'event-manager'),
            'name' => 'additional_ticket_types',
            'type' => 'repeater',
            'instructions' => __('Additional types of tickets.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'block',
            'button_label' => '',
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_5ae2e5bc94975',
                    'label' => __('Ticket name', 'event-manager'),
                    'name' => 'ticket_name',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                1 => array(
                    'key' => 'field_5ae2e64294977',
                    'label' => __('Maximum price', 'event-manager'),
                    'name' => 'maximum_price',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => __('SEK', 'event-manager'),
                    'maxlength' => '',
                ),
                2 => array(
                    'key' => 'field_5ae2e5d094976',
                    'label' => __('Minimum price', 'event-manager'),
                    'name' => 'minimum_price',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => __('SEK', 'event-manager'),
                    'maxlength' => '',
                ),
                3 => array(
                    'key' => 'field_5ae2e65394978',
                    'label' => __('Ticket type', 'event-manager'),
                    'name' => 'ticket_type',
                    'type' => 'radio',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'Standing' => __('Standing', 'event-manager'),
                        'Seated' => __('Seated', 'event-manager'),
                    ),
                    'allow_null' => 0,
                    'other_choice' => 0,
                    'save_other_choice' => 0,
                    'default_value' => '',
                    'layout' => 'horizontal',
                    'return_format' => 'value',
                ),
            ),
        ),
        33 => array(
            'key' => 'field_5ae2e0ececa4c',
            'label' => __('Price range', 'event-manager'),
            'name' => 'price_range',
            'type' => 'group',
            'instructions' => __('Information about the price range for tickets.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_5ae2e0fceca4d',
                    'label' => __('Seated minimum price', 'event-manager'),
                    'name' => 'seated_minimum_price',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => __('SEK', 'event-manager'),
                    'maxlength' => '',
                ),
                1 => array(
                    'key' => 'field_5ae2e168eca4e',
                    'label' => __('Seated maximum price', 'event-manager'),
                    'name' => 'seated_maximum_price',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => __('SEK', 'event-manager'),
                    'maxlength' => '',
                ),
                2 => array(
                    'key' => 'field_5ae2e16aeca4f',
                    'label' => __('Standing minimum price', 'event-manager'),
                    'name' => 'standing_minimum_price',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => __('SEK', 'event-manager'),
                    'maxlength' => '',
                ),
                3 => array(
                    'key' => 'field_5ae2e16ceca50',
                    'label' => __('Standing maximum price', 'event-manager'),
                    'name' => 'standing_maximum_price',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => __('SEK', 'event-manager'),
                    'maxlength' => '',
                ),
            ),
        ),
        34 => array(
            'key' => 'field_57f4f4ac7479f',
            'label' => __('Price group', 'event-manager'),
            'name' => 'booking_group',
            'type' => 'repeater',
            'instructions' => __('Add prices for group bookings.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'block',
            'button_label' => __('Add group', 'event-manager'),
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_57f4f6dc747a1',
                    'label' => __('Price', 'event-manager'),
                    'name' => 'price_group',
                    'type' => 'text',
                    'instructions' => __('Price for this group.', 'event-manager'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => __('SEK', 'event-manager'),
                    'maxlength' => '',
                ),
                1 => array(
                    'key' => 'field_57f4f74e747a2',
                    'label' => __('Min persons', 'event-manager'),
                    'name' => 'min_persons',
                    'type' => 'number',
                    'instructions' => __('Minimum number of people.', 'event-manager'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                2 => array(
                    'key' => 'field_57f4f765747a3',
                    'label' => __('Max persons', 'event-manager'),
                    'name' => 'max_persons',
                    'type' => 'number',
                    'instructions' => __('Maximum number of people.', 'event-manager'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
            ),
        ),
        35 => array(
            'key' => 'field_57611bd8acf1b',
            'label' => __('Price information', 'event-manager'),
            'name' => 'price_information',
            'type' => 'textarea',
            'instructions' => __('Write additional information about prices.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 3,
            'new_lines' => 'wpautop',
        ),
        36 => array(
            'key' => 'field_57b70267e1f32',
            'label' => __('Ticket includes', 'event-manager'),
            'name' => 'ticket_includes',
            'type' => 'textarea',
            'instructions' => __('Does the ticket include more than entry? Then write what\'s included in one ticket.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => __('e.g. entry, checkroom, meal', 'event-manager'),
            'maxlength' => '',
            'rows' => 3,
            'new_lines' => 'wpautop',
        ),
        37 => array(
            'key' => 'field_5b03c600cd81e',
            'label' => __('Contact', 'event-manager'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        38 => array(
            'key' => 'field_5b03c6f3cd820',
            'label' => __('Phone', 'event-manager'),
            'name' => 'contact_phone',
            'type' => 'text',
            'instructions' => __('Phone number to contact service.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        39 => array(
            'key' => 'field_5b03c671cd81f',
            'label' => __('Email', 'event-manager'),
            'name' => 'contact_email',
            'type' => 'email',
            'instructions' => __('Email to contact service.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        40 => array(
            'key' => 'field_5b03c744cd821',
            'label' => __('Contact information', 'event-manager'),
            'name' => 'contact_information',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => '',
            'new_lines' => '',
        ),
        41 => array(
            'key' => 'field_577a326b71ba8',
            'label' => __('Gallery', 'event-manager'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        42 => array(
            'key' => 'field_577a312acd95d',
            'label' => __('Gallery', 'event-manager'),
            'name' => 'gallery',
            'type' => 'gallery',
            'instructions' => __('Add images to this event.<br> Please upload images that are as large as possible and that are not sensitive to cropping (eg. images with text overlay).', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'min' => '',
            'max' => '',
            'insert' => 'append',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        43 => array(
            'key' => 'field_57a9d7f655152',
            'label' => __('Links', 'event-manager'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        44 => array(
            'key' => 'field_58188dfcfc3b9',
            'label' => __('Links', 'event-manager'),
            'name' => '',
            'type' => 'message',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => __('Add external links to different social media and streaming services.', 'event-manager'),
            'new_lines' => 'wpautop',
            'esc_html' => 0,
        ),
        45 => array(
            'key' => 'field_57a9d81f55153',
            'label' => __('Facebook', 'event-manager'),
            'name' => 'facebook',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
        ),
        46 => array(
            'key' => 'field_57a9d82b55154',
            'label' => __('Twitter', 'event-manager'),
            'name' => 'twitter',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
        ),
        47 => array(
            'key' => 'field_57a9d83355155',
            'label' => __('Instagram', 'event-manager'),
            'name' => 'instagram',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
        ),
        48 => array(
            'key' => 'field_57c82373297f1',
            'label' => __('Google Music', 'event-manager'),
            'name' => 'google_music',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
        ),
        49 => array(
            'key' => 'field_57c82396297f2',
            'label' => __('Apple Music', 'event-manager'),
            'name' => 'apple_music',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
        ),
        50 => array(
            'key' => 'field_57c823a8297f3',
            'label' => __('Spotify', 'event-manager'),
            'name' => 'spotify',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
        ),
        51 => array(
            'key' => 'field_57c826af782b0',
            'label' => __('Soundcloud', 'event-manager'),
            'name' => 'soundcloud',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
        ),
        52 => array(
            'key' => 'field_57c823d7297f4',
            'label' => __('Deezer', 'event-manager'),
            'name' => 'deezer',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
        ),
        53 => array(
            'key' => 'field_57a9d84055156',
            'label' => __('YouTube', 'event-manager'),
            'name' => 'youtube',
            'type' => 'repeater',
            'instructions' => __('Add one or multiple YouTube links.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'block',
            'button_label' => __('Add link', 'event-manager'),
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_57c8153ecca56',
                    'label' => __('YouTube link', 'event-manager'),
                    'name' => 'youtube_link',
                    'type' => 'url',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                ),
            ),
        ),
        54 => array(
            'key' => 'field_57a9d84955157',
            'label' => __('Vimeo', 'event-manager'),
            'name' => 'vimeo',
            'type' => 'repeater',
            'instructions' => __('Add one or multiple Vimeo links.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'block',
            'button_label' => __('Add link', 'event-manager'),
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_57c817b7a3395',
                    'label' => __('Vimeo link', 'event-manager'),
                    'name' => 'vimeo_link',
                    'type' => 'url',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                ),
            ),
        ),
        55 => array(
            'key' => 'field_5c593b9efbba0',
            'label' => __('Age', 'event-manager'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        56 => array(
            'key' => 'field_5c593bd1fbba1',
            'label' => __('Age group', 'event-manager'),
            'name' => 'age_group',
            'type' => 'group',
            'instructions' => __('Age group that the activity is addressed to.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_5c593d58fbba2',
                    'label' => __('From', 'event-manager'),
                    'name' => 'from',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => __('years', 'event-manager'),
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                1 => array(
                    'key' => 'field_5c593d92fbba3',
                    'label' => __('To', 'event-manager'),
                    'name' => 'to',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => __('years', 'event-manager'),
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'event',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));
}