<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_68d28f0c82ff4',
    'title' => __('Time & Place', 'api-event-manager'),
    'fields' => array(
        0 => array(
            'key' => 'field_68db9ef4c9d5d',
            'label' => __('Attendance mode', 'api-event-manager'),
            'name' => 'attendancemode',
            'aria-label' => '',
            'type' => 'button_group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 0,
            'choices' => array(
                'offline' => __('Offline', 'api-event-manager'),
                'online' => __('Online', 'api-event-manager'),
            ),
            'default_value' => __('offline', 'api-event-manager'),
            'return_format' => 'value',
            'allow_null' => 0,
            'allow_in_bindings' => 0,
            'layout' => 'horizontal',
        ),
        1 => array(
            'key' => 'field_68d28f0c845d0',
            'label' => __('Occasions', 'api-event-manager'),
            'name' => 'occasions',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => __('When is the event scheduled to take place? You have the option to establish a recurring schedule or specify up to 10 distinct dates and times.', 'api-event-manager'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 0,
            'layout' => 'block',
            'pagination' => 0,
            'min' => 1,
            'max' => 10,
            'collapsed' => '',
            'button_label' => __('Add occation', 'api-event-manager'),
            'rows_per_page' => 20,
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_68d28f0c8845b',
                    'label' => __('Repeat', 'api-event-manager'),
                    'name' => 'repeat',
                    'aria-label' => '',
                    'type' => 'button_group',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'is_publicly_hidden' => 0,
                    'is_privately_hidden' => 0,
                    'choices' => array(
                        'no' => __('No', 'api-event-manager'),
                        'byWeek' => __('Weekly occasion', 'api-event-manager'),
                        'byMonth' => __('Monthly occasion', 'api-event-manager'),
                    ),
                    'default_value' => __('no', 'api-event-manager'),
                    'return_format' => 'value',
                    'allow_null' => 0,
                    'allow_in_bindings' => 0,
                    'layout' => 'horizontal',
                    'parent_repeater' => 'field_68d28f0c845d0',
                ),
                1 => array(
                    'key' => 'field_68d28f0c887c5',
                    'label' => __('Every', 'api-event-manager'),
                    'name' => 'weeksInterval',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_68d28f0c8845b',
                                'operator' => '==',
                                'value' => 'byWeek',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 1,
                    'min' => 1,
                    'max' => '',
                    'placeholder' => '',
                    'step' => '',
                    'prepend' => '',
                    'append' => __('week/weeks', 'api-event-manager'),
                    'parent_repeater' => 'field_68d28f0c845d0',
                ),
                2 => array(
                    'key' => 'field_68d28f0c88c7c',
                    'label' => __('Every', 'api-event-manager'),
                    'name' => 'monthsInterval',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_68d28f0c8845b',
                                'operator' => '==',
                                'value' => 'byMonth',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'is_publicly_hidden' => 0,
                    'is_privately_hidden' => 0,
                    'default_value' => 1,
                    'min' => 1,
                    'max' => '',
                    'allow_in_bindings' => 1,
                    'placeholder' => '',
                    'step' => '',
                    'prepend' => '',
                    'append' => __('month/months', 'api-event-manager'),
                    'parent_repeater' => 'field_68d28f0c845d0',
                ),
                3 => array(
                    'key' => 'field_68d28f0c88f84',
                    'label' => __('Day', 'api-event-manager'),
                    'name' => 'weekDays',
                    'aria-label' => '',
                    'type' => 'checkbox',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_68d28f0c8845b',
                                'operator' => '==',
                                'value' => 'byWeek',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'https://schema.org/Monday' => __('Mon', 'api-event-manager'),
                        'https://schema.org/Tuesday' => __('Tue', 'api-event-manager'),
                        'https://schema.org/Wednesday' => __('Wed', 'api-event-manager'),
                        'https://schema.org/Thursday' => __('Thu', 'api-event-manager'),
                        'https://schema.org/Friday' => __('Fri', 'api-event-manager'),
                        'https://schema.org/Saturday' => __('Sat', 'api-event-manager'),
                        'https://schema.org/Sunday' => __('Sun', 'api-event-manager'),
                    ),
                    'default_value' => array(
                    ),
                    'return_format' => 'value',
                    'allow_custom' => 0,
                    'layout' => 'horizontal',
                    'toggle' => 0,
                    'save_custom' => 0,
                    'custom_choice_button_text' => 'Lägg till nytt val',
                    'parent_repeater' => 'field_68d28f0c845d0',
                ),
                4 => array(
                    'key' => 'field_68d28f0c89453',
                    'label' => __('Day', 'api-event-manager'),
                    'name' => 'monthDay',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_68d28f0c8845b',
                                'operator' => '==',
                                'value' => 'byMonth',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'day' => __('Day', 'api-event-manager'),
                        'first' => __('First', 'api-event-manager'),
                        'second' => __('Second', 'api-event-manager'),
                        'third' => __('Third', 'api-event-manager'),
                        'fourth' => __('Fourth', 'api-event-manager'),
                        'last' => __('Last', 'api-event-manager'),
                    ),
                    'default_value' => __('day', 'api-event-manager'),
                    'return_format' => 'value',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'placeholder' => '',
                    'allow_custom' => 0,
                    'search_placeholder' => '',
                    'parent_repeater' => 'field_68d28f0c845d0',
                    'create_options' => 0,
                    'save_options' => 0,
                ),
                5 => array(
                    'key' => 'field_68d28f0c897e3',
                    'label' => __('By number', 'api-event-manager'),
                    'name' => 'monthDayNumber',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_68d28f0c89453',
                                'operator' => '==',
                                'value' => 'day',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 1,
                    'min' => 1,
                    'max' => 31,
                    'placeholder' => '',
                    'step' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_68d28f0c845d0',
                ),
                6 => array(
                    'key' => 'field_68d28f0c89b49',
                    'label' => __('Date', 'api-event-manager'),
                    'name' => 'date',
                    'aria-label' => '',
                    'type' => 'date_picker',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'Y-m-d',
                    'return_format' => 'Y-m-d',
                    'first_day' => 1,
                    'parent_repeater' => 'field_68d28f0c845d0',
                    'default_to_current_date' => 0,
                ),
                7 => array(
                    'key' => 'field_68d28f0c8a008',
                    'label' => __('Until Date', 'api-event-manager'),
                    'name' => 'untilDate',
                    'aria-label' => '',
                    'type' => 'date_picker',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_68d28f0c8845b',
                                'operator' => '!=',
                                'value' => 'no',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'Y-m-d',
                    'return_format' => 'Y-m-d',
                    'first_day' => 1,
                    'parent_repeater' => 'field_68d28f0c845d0',
                    'default_to_current_date' => 0,
                ),
                8 => array(
                    'key' => 'field_68d28f0c8a391',
                    'label' => __('Start time', 'api-event-manager'),
                    'name' => 'startTime',
                    'aria-label' => '',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i:s',
                    'return_format' => 'H:i:s',
                    'parent_repeater' => 'field_68d28f0c845d0',
                ),
                9 => array(
                    'key' => 'field_68d28f0c8a6ff',
                    'label' => __('End time', 'api-event-manager'),
                    'name' => 'endTime',
                    'aria-label' => '',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i:s',
                    'return_format' => 'H:i:s',
                    'parent_repeater' => 'field_68d28f0c845d0',
                ),
                10 => array(
                    'key' => 'field_68d28f0c8abbe',
                    'label' => __('Booking page URL', 'api-event-manager'),
                    'name' => 'url',
                    'aria-label' => '',
                    'type' => 'url',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'parent_repeater' => 'field_68d28f0c845d0',
                ),
            ),
        ),
        2 => array(
            'key' => 'field_68d28f0c8493c',
            'label' => __('Prices', 'api-event-manager'),
            'name' => 'pricesList',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => __('You have the option to offer multiple pricing tiers to accommodate attendees of different age groups. By not adding any ticket variations, your event will show up as free of charge.', 'api-event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 0,
            'layout' => 'block',
            'pagination' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => '',
            'button_label' => __('Add Ticket / Variation', 'api-event-manager'),
            'rows_per_page' => 20,
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_68d28f0c8f518',
                    'label' => __('Price Label', 'api-event-manager'),
                    'name' => 'priceLabel',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => __('Standard Ticket', 'api-event-manager'),
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_68d28f0c8493c',
                ),
                1 => array(
                    'key' => 'field_68d28f0c8f9e1',
                    'label' => __('Price', 'api-event-manager'),
                    'name' => 'price',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 100,
                    'min' => '',
                    'max' => '',
                    'placeholder' => '',
                    'step' => '',
                    'prepend' => '',
                    'append' => __('$', 'api-event-manager'),
                    'parent_repeater' => 'field_68d28f0c8493c',
                ),
            ),
        ),
        3 => array(
            'key' => 'field_68d28f0c84e03',
            'label' => __('Location name', 'api-event-manager'),
            'name' => 'locationName',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_68db9ef4c9d5d',
                        'operator' => '==',
                        'value' => 'offline',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 0,
            'default_value' => '',
            'maxlength' => '',
            'allow_in_bindings' => 0,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        4 => array(
            'key' => 'field_68d28f0c851a1',
            'label' => __('Location address', 'api-event-manager'),
            'name' => 'locationAddress',
            'aria-label' => '',
            'type' => 'google_map',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_68db9ef4c9d5d',
                        'operator' => '==',
                        'value' => 'offline',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 0,
            'center_lat' => '56.0467',
            'center_lng' => '12.6944',
            'zoom' => '',
            'height' => '',
            'allow_in_bindings' => 0,
        ),
        5 => array(
            'key' => 'field_68dba07119269',
            'label' => __('Online attendence url', 'api-event-manager'),
            'name' => 'onlineAttendenceUrl',
            'aria-label' => '',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_68db9ef4c9d5d',
                        'operator' => '==',
                        'value' => 'online',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 0,
            'default_value' => '',
            'allow_in_bindings' => 0,
            'placeholder' => '',
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'event',
            ),
        ),
    ),
    'menu_order' => 3,
    'position' => 'acf_after_title',
    'style' => 'default',
    'label_placement' => 'left',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
        0 => 'permalink',
        1 => 'the_content',
        2 => 'excerpt',
        3 => 'discussion',
        4 => 'comments',
        5 => 'slug',
        6 => 'format',
        7 => 'page_attributes',
        8 => 'featured_image',
        9 => 'categories',
        10 => 'tags',
        11 => 'send-trackbacks',
    ),
    'active' => true,
    'description' => '',
    'show_in_rest' => 1,
));
}