<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_58ab055a4b3b8',
    'title' => 'Nitifikationer',
    'fields' => array(
        0 => array(
            'sub_fields' => array(
                0 => array(
                    'default_value' => '',
                    'new_lines' => '',
                    'maxlength' => '',
                    'placeholder' => __('Vad vill du säga? ', 'event-manager'),
                    'rows' => 4,
                    'key' => 'field_58ab0585c586f',
                    'label' => __('Meddelande', 'event-manager'),
                    'name' => 'message',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                1 => array(
                    'default_value' => 5,
                    'min' => '',
                    'max' => '',
                    'step' => 1,
                    'placeholder' => '',
                    'prepend' => __('Delay', 'event-manager'),
                    'append' => __('minuter', 'event-manager'),
                    'key' => 'field_58ab05cac5870',
                    'label' => __('Fördröjning', 'event-manager'),
                    'name' => 'timeout',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                ),
            ),
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => __('Lägg till notifiering', 'event-manager'),
            'collapsed' => 'field_58ab0585c586f',
            'key' => 'field_58ab055ec586e',
            'label' => __('Ankomstmeddelande', 'event-manager'),
            'name' => 'guide_arrival_notice',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
        1 => array(
            'sub_fields' => array(
                0 => array(
                    'default_value' => '',
                    'new_lines' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'rows' => 4,
                    'key' => 'field_58ab06528a9b1',
                    'label' => __('Meddelande', 'event-manager'),
                    'name' => 'message',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                1 => array(
                    'default_value' => 10,
                    'min' => 0,
                    'max' => '',
                    'step' => 1,
                    'placeholder' => '',
                    'prepend' => __('Delay', 'event-manager'),
                    'append' => __('minuter', 'event-manager'),
                    'key' => 'field_58ab06698a9b2',
                    'label' => __('Fördröjning', 'event-manager'),
                    'name' => 'timeout',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                ),
            ),
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => __('Lägg till notifiering', 'event-manager'),
            'collapsed' => '',
            'key' => 'field_58ab063f8a9b0',
            'label' => __('Avresemeddelande', 'event-manager'),
            'name' => 'guide_departure_notice',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'taxonomy',
                'operator' => '==',
                'value' => 'guidegroup',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
    'local' => 'php',
));
}