<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_589497ca3741e',
    'title' => 'Grundläggande guideinställningar',
    'fields' => array(
        0 => array(
            'placement' => 'left',
            'endpoint' => 0,
            'key' => 'field_58949857fc7b0',
            'label' => __('Genrellt	', 'event-manager'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
        1 => array(
            'tabs' => 'all',
            'toolbar' => 'basic',
            'media_upload' => 0,
            'default_value' => '',
            'delay' => 0,
            'key' => 'field_58949813a052c',
            'label' => __('Beskrivning', 'event-manager'),
            'name' => 'guide_description',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
        2 => array(
            'placement' => 'left',
            'endpoint' => 0,
            'key' => 'field_5894987dfc7b1',
            'label' => __('Media', 'event-manager'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
        3 => array(
            'library' => 'all',
            'min' => '',
            'max' => 10,
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => 'jpg,jpeg,png',
            'insert' => 'append',
            'key' => 'field_589dc93cde2d7',
            'label' => __('Guidebilder', 'event-manager'),
            'name' => 'guide_images',
            'type' => 'gallery',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => 'secondary-panel',
                'id' => '',
            ),
        ),
        4 => array(
            'placement' => 'top',
            'endpoint' => 0,
            'key' => 'field_5899a94bff0ec',
            'label' => __('Innehållsobjekt', 'event-manager'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
        5 => array(
            'sub_fields' => array(
                0 => array(
                    'placement' => 'top',
                    'endpoint' => 0,
                    'key' => 'field_589db03e16e51',
                    'label' => __('Genrellt	', 'event-manager'),
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                1 => array(
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => __('Titeln på innehållsobjektet', 'event-manager'),
                    'prepend' => '',
                    'append' => '',
                    'key' => 'field_5899aab938d3d',
                    'label' => __('Objektets titel', 'event-manager'),
                    'name' => 'guide_object_title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '75',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                2 => array(
                    'default_value' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                    'placeholder' => '',
                    'prepend' => __('#', 'event-manager'),
                    'append' => '',
                    'key' => 'field_589dcc1a7deb3',
                    'label' => __('Utställnings ID', 'event-manager'),
                    'name' => 'guide_object_id',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                3 => array(
                    'tabs' => 'all',
                    'toolbar' => 'basic',
                    'media_upload' => 1,
                    'default_value' => '',
                    'delay' => 0,
                    'key' => 'field_5899aae338d3e',
                    'label' => __('Objektbeskrivning', 'event-manager'),
                    'name' => 'guide_object_description',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                4 => array(
                    'placement' => 'top',
                    'endpoint' => 0,
                    'key' => 'field_589db05816e52',
                    'label' => __('Media', 'event-manager'),
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                5 => array(
                    'library' => 'all',
                    'min' => '',
                    'max' => 10,
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => 'jpg,jpeg,png',
                    'insert' => 'append',
                    'key' => 'field_5899ab0338d3f',
                    'label' => __('Objektets bild', 'event-manager'),
                    'name' => 'guide_object_image',
                    'type' => 'gallery',
                    'instructions' => __('En eller flera bilder i jpg eller png format', 'event-manager'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                6 => array(
                    'return_format' => 'array',
                    'library' => 'uploadedTo',
                    'min_size' => '',
                    'max_size' => 50,
                    'mime_types' => 'm4a,aac,mp3',
                    'key' => 'field_5899ab2c38d40',
                    'label' => __('Ljud', 'event-manager'),
                    'name' => 'guide_object_audio',
                    'type' => 'file',
                    'instructions' => __('En ljudfil som beskriver objektet. Filen bör vara rimligt komprimerad och vara av AAC+ V2 (m4a) format eller Mp3.', 'event-manager'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                7 => array(
                    'return_format' => 'array',
                    'library' => 'uploadedTo',
                    'min_size' => '',
                    'max_size' => 50,
                    'mime_types' => 'mp4',
                    'key' => 'field_5899ac03acc12',
                    'label' => __('Film', 'event-manager'),
                    'name' => 'guide_object_video',
                    'type' => 'file',
                    'instructions' => __('En kortare video som beskrivet objektet. Tänk på att ett mindre filformat oftast resulterar i fler visningar. Föredraget format: Mp4. ', 'event-manager'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                8 => array(
                    'placement' => 'top',
                    'endpoint' => 0,
                    'key' => 'field_589db08d16e53',
                    'label' => __('Länkar	', 'event-manager'),
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                9 => array(
                    'sub_fields' => array(
                        0 => array(
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'key' => 'field_5899e5e1a583d',
                            'label' => __('Länknamn', 'event-manager'),
                            'name' => 'guide_object_link_title',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                        1 => array(
                            'default_value' => '',
                            'placeholder' => '',
                            'key' => 'field_5899e64fa583e',
                            'label' => __('Webbadress', 'event-manager'),
                            'name' => 'guide_object_link_url',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                    ),
                    'min' => 0,
                    'max' => 20,
                    'layout' => 'block',
                    'button_label' => __('Lägg till länk', 'event-manager'),
                    'collapsed' => 'field_5899e5e1a583d',
                    'key' => 'field_5899e5c8a583c',
                    'label' => __('Länkar och ytterligare resurser', 'event-manager'),
                    'name' => 'guide_object_links',
                    'type' => 'repeater',
                    'instructions' => __('Lägg till länkar som har mer information om objektet. Det kan till exempel vara en hemsida eller fil (på webben). ', 'event-manager'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => 'secondary-panel',
                        'id' => '',
                    ),
                ),
                10 => array(
                    'placement' => 'top',
                    'endpoint' => 0,
                    'key' => 'field_589db114078de',
                    'label' => __('Beacons', 'event-manager'),
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_58949a8f0c4cd',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                11 => array(
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'key' => 'field_589db29081803',
                    'label' => __('Objektets beacon ID', 'event-manager'),
                    'name' => 'guide_object_beacon_id',
                    'type' => 'text',
                    'instructions' => __('Ett unikt id för att identifiera en specifik beacon.', 'event-manager'),
                    'required' => 1,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_58949a8f0c4cd',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '60',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                12 => array(
                    'default_value' => 5,
                    'min' => 1,
                    'max' => 70,
                    'step' => 1,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => __('meter', 'event-manager'),
                    'key' => 'field_589dc6da3611c',
                    'label' => __('Maximalt avstånd till beacon. ', 'event-manager'),
                    'name' => 'guide_object_beacon_distance',
                    'type' => 'number',
                    'instructions' => __('Avstånd som ska trigga beacon-sändare.', 'event-manager'),
                    'required' => 1,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_58949a8f0c4cd',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '40',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                13 => array(
                    'placement' => 'top',
                    'endpoint' => 0,
                    'key' => 'field_58a5c081f4193',
                    'label' => __('Synbarhet', 'event-manager'),
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                14 => array(
                    'default_value' => 0,
                    'message' => __('Ja, visa detta objekt', 'event-manager'),
                    'ui' => 0,
                    'ui_on_text' => __('Visa', 'event-manager'),
                    'ui_off_text' => __('Dölj', 'event-manager'),
                    'key' => 'field_58a5c098f4194',
                    'label' => __('Objektets synbarhet', 'event-manager'),
                    'name' => 'guide_object_active',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                15 => array(
                    'key' => 'field_58ad84a12d5ac',
                    'label' => __('Unikt ID', 'event-manager'),
                    'name' => 'guide_object_uid',
                    'type' => 'unique_id',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
            ),
            'min' => 1,
            'max' => 500,
            'layout' => 'block',
            'button_label' => __('Lägg till nytt objekt', 'event-manager'),
            'collapsed' => 'field_5899aab938d3d',
            'key' => 'field_5899cc4b59d94',
            'label' => __('Innehåll (tavlor, konstverk, träd etc.)', 'event-manager'),
            'name' => 'guide_content_objects',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
        6 => array(
            'placement' => 'top',
            'endpoint' => 0,
            'key' => 'field_58ab0c6354b09',
            'label' => __('Beacons', 'event-manager'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
        7 => array(
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'key' => 'field_58ac5c65cdffe',
            'label' => __('Beacon namnrymd', 'event-manager'),
            'name' => 'guide_beacon_namespace',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
        8 => array(
            'sub_fields' => array(
                0 => array(
                    'post_type' => array(
                        0 => 'location',
                    ),
                    'taxonomy' => array(
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'return_format' => 'id',
                    'ui' => 1,
                    'key' => 'field_58ab0c9554b0a',
                    'label' => __('Plats', 'event-manager'),
                    'name' => 'location',
                    'type' => 'post_object',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '36',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                1 => array(
                    'multiple' => 1,
                    'allow_null' => 0,
                    'choices' => array(
                    ),
                    'default_value' => array(
                    ),
                    'ui' => 1,
                    'ajax' => 1,
                    'placeholder' => '',
                    'return_format' => 'value',
                    'key' => 'field_58ab0cf054b0b',
                    'label' => __('Innehållsobjekt', 'event-manager'),
                    'name' => 'objects',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '30',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                2 => array(
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'key' => 'field_58ac54a64bb06',
                    'label' => __('Beacon ID', 'event-manager'),
                    'name' => 'beacon',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '30',
                        'class' => '',
                        'id' => '',
                    ),
                ),
            ),
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => __('Lägg till grupp', 'event-manager'),
            'collapsed' => 'field_58ab0cf054b0b',
            'key' => 'field_58ab0b4454b08',
            'label' => __('Grupper av beacons', 'event-manager'),
            'name' => 'guide_beacon',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'guide',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'field',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => 'Manage main guide object details.',
    'local' => 'php',
));
}