<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_589dcf7e047a8',
    'title' => __('Inställningar för kategori', 'event-manager'),
    'fields' => array(
        0 => array(
            'key' => 'field_58ac3daed44c3',
            'label' => __('Aktiv', 'event-manager'),
            'name' => 'guide_taxonomy_active',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 1,
            'message' => __('Ja, den här gruppen är aktiv.', 'event-manager'),
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        1 => array(
            'key' => 'field_589dcf9661090',
            'label' => __('Logotyp', 'event-manager'),
            'name' => 'guide_taxonomy_logotype',
            'type' => 'image',
            'instructions' => __('En logotyp som visas i samband med guider kopplade till kategorin.', 'event-manager'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'uploadedTo',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => 'svg, png',
        ),
        2 => array(
            'key' => 'field_589dd18acd51f',
            'label' => __('Färg', 'event-manager'),
            'name' => 'guide_taxonomy_color',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => 'colorpicker',
                'id' => '',
            ),
            'default_value' => '#FFFFFF',
        ),
        3 => array(
            'key' => 'field_58a2d24ca466c',
            'label' => __('Stämningsbild', 'event-manager'),
            'name' => 'guide_taxonomy_image',
            'type' => 'image',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => 'png, jpg, jpeg',
        ),
        4 => array(
            'key' => 'field_58ac3ca740387',
            'label' => __('Plats', 'event-manager'),
            'name' => 'guide_taxonomy_location',
            'type' => 'post_object',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'post_type' => array(
                0 => 'location',
            ),
            'taxonomy' => array(
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'return_format' => 'id',
            'ui' => 1,
        ),
        5 => array(
            'key' => 'field_58b4091bc9dbf',
            'label' => __('Platsens radie', 'event-manager'),
            'name' => 'guide_taxonomy_radius',
            'type' => 'number',
            'instructions' => __('Visa den här platsen inom en radie av X meter', 'event-manager'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 50,
            'min' => 50,
            'max' => 10000,
            'step' => 50,
            'placeholder' => '',
            'prepend' => '',
            'append' => __('meter', 'event-manager'),
        ),
        6 => array(
            'key' => 'field_58ad7751e92af',
            'label' => __('Tillåt endast underordnade platser', 'event-manager'),
            'name' => 'guide_taxonomy_sublocations',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 0,
            'message' => __('Ja, filtrera bort samtliga platser som inte matchar förälderplatsen', 'event-manager'),
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        7 => array(
            'key' => 'field_58ac5da5ed8ff',
            'label' => __('Platsen har trådlöst nätverk', 'event-manager'),
            'name' => 'guide_taxonomy_wifi',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 1,
            'message' => __('Ja, den här platsen har full täckning', 'event-manager'),
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        8 => array(
            'key' => 'field_58ac5dc8ed900',
            'label' => __('Karta', 'event-manager'),
            'name' => 'guide_taxonomy_map',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 1,
            'message' => __('Ja, den här platsen kan använda google maps.', 'event-manager'),
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        9 => array(
            'key' => 'field_5f60b23272220',
            'label' => __('Grupp', 'event-manager'),
            'name' => 'guide_taxonomy_user_group',
            'type' => 'taxonomy',
            'instructions' => __('Välj vilken användargrupp som kategorin tillhör.', 'event-manager'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'taxonomy' => 'user_groups',
            'field_type' => 'select',
            'allow_null' => 0,
            'add_term' => 1,
            'save_terms' => 1,
            'load_terms' => 0,
            'return_format' => 'id',
            'multiple' => 0,
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'taxonomy',
                'operator' => '==',
                'value' => 'guidegroup',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));
}