<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_5f68a3350351d',
    'title' => __('Interactive Guide', 'event-manager'),
    'fields' => array(
        0 => array(
            'key' => 'field_5f68a43a88018',
            'label' => __('Start title', 'event-manager'),
            'name' => 'start_guide_label',
            'type' => 'text',
            'instructions' => __('Label to display on start guide action.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        1 => array(
            'key' => 'field_5f68b2656239c',
            'label' => __('Steps', 'event-manager'),
            'name' => 'steps',
            'type' => 'flexible_content',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layouts' => array(
                'layout_5f68bc561a427' => array(
                    'key' => 'layout_5f68bc561a427',
                    'name' => 'start',
                    'label' => __('Start', 'event-manager'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_5f68bc7b1a428',
                            'label' => 'Introduction text',
                            'name' => 'text',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        1 => array(
                            'key' => 'field_5f68be8c4b154',
                            'label' => 'Start guide label',
                            'name' => 'start_guide_label',
                            'type' => 'text',
                            'instructions' => 'Text to display on action that triggers the guide to start.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        2 => array(
                            'key' => 'field_5f68bf09a8254',
                            'label' => 'Image',
                            'name' => 'image',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => '',
                            'min' => 0,
                            'max' => 1,
                            'layout' => 'block',
                            'button_label' => '',
                            'sub_fields' => array(
                                0 => array(
                                    'key' => 'field_5f68bf39a8255',
                                    'label' => 'Source',
                                    'name' => 'source',
                                    'type' => 'radio',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        'uploaded' => 'Uploaded',
                                        'url' => 'URL',
                                    ),
                                    'allow_null' => 0,
                                    'other_choice' => 0,
                                    'default_value' => '',
                                    'layout' => 'horizontal',
                                    'return_format' => 'value',
                                    'save_other_choice' => 0,
                                ),
                                1 => array(
                                    'key' => 'field_5f68bf83a8256',
                                    'label' => 'Image',
                                    'name' => 'image',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => array(
                                        0 => array(
                                            0 => array(
                                                'field' => 'field_5f68bf39a8255',
                                                'operator' => '==',
                                                'value' => 'uploaded',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'array',
                                    'preview_size' => 'medium',
                                    'library' => 'all',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => 'png, jpeg, jpg, svg, gif',
                                ),
                                2 => array(
                                    'key' => 'field_5f68c0a6406d8',
                                    'label' => 'URL',
                                    'name' => 'url',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => array(
                                        0 => array(
                                            0 => array(
                                                'field' => 'field_5f68bf39a8255',
                                                'operator' => '==',
                                                'value' => 'url',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                3 => array(
                                    'key' => 'field_5f68c0f2dd3e2',
                                    'label' => 'Aspect ratio',
                                    'name' => 'aspect_ratio',
                                    'type' => 'select',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        '1:1' => '1:1',
                                        '4:3' => '4:3',
                                        '16:9' => '16:9',
                                    ),
                                    'default_value' => array(
                                    ),
                                    'allow_null' => 1,
                                    'multiple' => 0,
                                    'ui' => 0,
                                    'return_format' => 'value',
                                    'ajax' => 0,
                                    'placeholder' => '',
                                ),
                            ),
                        ),
                    ),
                    'min' => '',
                    'max' => '1',
                ),
                'layout_5f68b3585a3fc' => array(
                    'key' => 'layout_5f68b3585a3fc',
                    'name' => 'chapter',
                    'label' => __('Chapter', 'event-manager'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_5f68b68e6239e',
                            'label' => 'Title',
                            'name' => 'title',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                'layout_5f68b70d623a2' => array(
                    'key' => 'layout_5f68b70d623a2',
                    'name' => 'bot',
                    'label' => __('Bot', 'event-manager'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_5f68b717623a3',
                            'label' => 'Text',
                            'name' => 'text',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                'layout_5f68b7d8e8051' => array(
                    'key' => 'layout_5f68b7d8e8051',
                    'name' => 'image',
                    'label' => __('Image', 'event-manager'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_5f68ba84f4a39',
                            'label' => 'Source',
                            'name' => 'source',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'uploaded' => 'Uploaded',
                                'url' => 'URL',
                            ),
                            'allow_null' => 0,
                            'other_choice' => 0,
                            'default_value' => '',
                            'layout' => 'horizontal',
                            'return_format' => 'value',
                            'save_other_choice' => 0,
                        ),
                        1 => array(
                            'key' => 'field_5f68b7f2e8052',
                            'label' => 'Image',
                            'name' => 'image',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_5f68ba84f4a39',
                                        'operator' => '==',
                                        'value' => 'uploaded',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'preview_size' => 'medium',
                            'library' => 'uploadedTo',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => 'png, jpeg, jpg, svg, gif',
                        ),
                        2 => array(
                            'key' => 'field_5f68ba65f4a38',
                            'label' => 'URL',
                            'name' => 'url',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_5f68ba84f4a39',
                                        'operator' => '==',
                                        'value' => 'url',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        3 => array(
                            'key' => 'field_5f68b86abd997',
                            'label' => 'Aspect ratio',
                            'name' => 'aspect_ratio',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                '1:1' => '1:1',
                                '4:3' => '4:3',
                                '16:9' => '16:9',
                            ),
                            'default_value' => array(
                            ),
                            'allow_null' => 1,
                            'multiple' => 0,
                            'ui' => 0,
                            'return_format' => 'value',
                            'ajax' => 0,
                            'placeholder' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                'layout_5f6999c722cbb' => array(
                    'key' => 'layout_5f6999c722cbb',
                    'name' => 'prompt',
                    'label' => __('Prompt', 'event-manager'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_5f6999f122cbc',
                            'label' => 'Alternatives',
                            'name' => 'alternatives',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => '',
                            'min' => 1,
                            'max' => 0,
                            'layout' => 'block',
                            'button_label' => '',
                            'sub_fields' => array(
                                0 => array(
                                    'key' => 'field_5f699a0322cbd',
                                    'label' => 'Answer',
                                    'name' => 'answer',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                1 => array(
                                    'key' => 'field_5f699ac322cbe',
                                    'label' => 'Follow up messages',
                                    'name' => 'follow_up',
                                    'type' => 'repeater',
                                    'instructions' => 'List of follow up messages that responds to the answer.',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'collapsed' => '',
                                    'min' => 0,
                                    'max' => 0,
                                    'layout' => 'block',
                                    'button_label' => '',
                                    'sub_fields' => array(
                                        0 => array(
                                            'key' => 'field_5f699ae922cbf',
                                            'label' => 'Message',
                                            'name' => 'message',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 1,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'maxlength' => '',
                                        ),
                                    ),
                                ),
                            ),
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                'layout_5f699e205015c' => array(
                    'key' => 'layout_5f699e205015c',
                    'name' => 'dialog',
                    'label' => __('Dialog', 'event-manager'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_5f699f3150162',
                            'label' => 'Title',
                            'name' => 'title',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        1 => array(
                            'key' => 'field_5f699f3a50163',
                            'label' => 'Insctructions',
                            'name' => 'insctructions',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        2 => array(
                            'key' => 'field_5f699f4650164',
                            'label' => 'Message',
                            'name' => 'message',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        3 => array(
                            'key' => 'field_5f699e4a50161',
                            'label' => 'Icon',
                            'name' => 'icon',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'talk' => 'Talk',
                                'look' => 'Look',
                                'question' => 'Question',
                            ),
                            'default_value' => array(
                            ),
                            'allow_null' => 1,
                            'multiple' => 0,
                            'ui' => 0,
                            'return_format' => 'value',
                            'ajax' => 0,
                            'placeholder' => '',
                        ),
                        4 => array(
                            'key' => 'field_5f699e205015d',
                            'label' => 'Alternatives',
                            'name' => 'alternatives',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => '',
                            'min' => 1,
                            'max' => 0,
                            'layout' => 'block',
                            'button_label' => '',
                            'sub_fields' => array(
                                0 => array(
                                    'key' => 'field_5f699e205015e',
                                    'label' => 'Answer',
                                    'name' => 'answer',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                1 => array(
                                    'key' => 'field_5f69be5b2d957',
                                    'label' => 'Correct',
                                    'name' => 'correct',
                                    'type' => 'true_false',
                                    'instructions' => 'Set to no if the dialog shall repeat itself until a correct alternative is answered.',
                                    'required' => 0,
                                    'conditional_logic' => array(
                                        0 => array(
                                            0 => array(
                                                'field' => 'field_5f699e205015d',
                                                'operator' => '>',
                                                'value' => '1',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'message' => '',
                                    'default_value' => 1,
                                    'ui' => 1,
                                    'ui_on_text' => '',
                                    'ui_off_text' => '',
                                ),
                                2 => array(
                                    'key' => 'field_5f699e205015f',
                                    'label' => 'Follow up messages',
                                    'name' => 'follow_up',
                                    'type' => 'repeater',
                                    'instructions' => 'List of follow up messages that responds to the answer.',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'collapsed' => '',
                                    'min' => 0,
                                    'max' => 0,
                                    'layout' => 'block',
                                    'button_label' => '',
                                    'sub_fields' => array(
                                        0 => array(
                                            'key' => 'field_5f699e2050160',
                                            'label' => 'Message',
                                            'name' => 'message',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 1,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'maxlength' => '',
                                        ),
                                    ),
                                ),
                            ),
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                'layout_5f69fb94c188b' => array(
                    'key' => 'layout_5f69fb94c188b',
                    'name' => 'finish',
                    'label' => __('Finish', 'event-manager'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_5f68a5c605ada',
                            'label' => 'Header title',
                            'name' => 'header_title',
                            'type' => 'text',
                            'instructions' => 'Title to display in finish screen header.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        1 => array(
                            'key' => 'field_5f68aa923521c',
                            'label' => 'Body title',
                            'name' => 'body_title',
                            'type' => 'text',
                            'instructions' => 'Title to display in finish screen body.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        2 => array(
                            'key' => 'field_5f68aaa83521d',
                            'label' => 'Body content',
                            'name' => 'body_content',
                            'type' => 'text',
                            'instructions' => 'Text to display on finish step body.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        3 => array(
                            'key' => 'field_5f68a63cd0fe4',
                            'label' => 'Images',
                            'name' => 'images',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => '',
                            'min' => 0,
                            'max' => 0,
                            'layout' => 'row',
                            'button_label' => '',
                            'sub_fields' => array(
                                0 => array(
                                    'key' => 'field_5f6a0c9234e4b',
                                    'label' => 'Source',
                                    'name' => 'source',
                                    'type' => 'radio',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        'uploaded' => 'Uploaded',
                                        'url' => 'URL',
                                    ),
                                    'allow_null' => 0,
                                    'other_choice' => 0,
                                    'default_value' => '',
                                    'layout' => 'vertical',
                                    'return_format' => 'value',
                                    'save_other_choice' => 0,
                                ),
                                1 => array(
                                    'key' => 'field_5f68a5d605adb',
                                    'label' => 'Image',
                                    'name' => 'image',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => array(
                                        0 => array(
                                            0 => array(
                                                'field' => 'field_5f6a0c9234e4b',
                                                'operator' => '==',
                                                'value' => 'uploaded',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'array',
                                    'preview_size' => 'medium',
                                    'library' => 'uploadedTo',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => 'png, jpeg, jpg, svg, gif',
                                ),
                                2 => array(
                                    'key' => 'field_5f6a0d0f34e4c',
                                    'label' => 'URL',
                                    'name' => 'url',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => array(
                                        0 => array(
                                            0 => array(
                                                'field' => 'field_5f6a0c9234e4b',
                                                'operator' => '==',
                                                'value' => 'url',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                            ),
                        ),
                        4 => array(
                            'key' => 'field_5f68a6bb0ee01',
                            'label' => 'Share text',
                            'name' => 'share_text',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        5 => array(
                            'key' => 'field_5f68a6d00ee02',
                            'label' => 'Share image',
                            'name' => 'share_image',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'preview_size' => 'medium',
                            'library' => 'uploadedTo',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => 'png, jpeg, jpg, svg, gif',
                        ),
                    ),
                    'min' => '',
                    'max' => '1',
                ),
            ),
            'button_label' => __('Add Row', 'event-manager'),
            'min' => '',
            'max' => '',
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'interactive-guide',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));
}