<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_5f68a3350351d',
    'title' => __('Interactive Guide', 'event-manager'),
    'fields' => array(
        0 => array(
            'key' => 'field_5f68b2656239c',
            'label' => __('Steps', 'event-manager'),
            'name' => 'steps',
            'type' => 'flexible_content',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layouts' => array(
                'layout_5f68bc561a427' => array(
                    'key' => 'layout_5f68bc561a427',
                    'name' => 'start',
                    'label' => __('Start', 'event-manager'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_5f6aff0740bda',
                            'label' => '',
                            'name' => '',
                            'type' => 'message',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => 'This is the first step for an interactive guide. It displays a text message, image and a button to start the guide.',
                            'new_lines' => 'wpautop',
                            'esc_html' => 0,
                        ),
                        1 => array(
                            'key' => 'field_5f68bc7b1a428',
                            'label' => 'Introduction text',
                            'name' => 'introduction_text',
                            'type' => 'text',
                            'instructions' => 'E.g. Hi and welcome to xx that is shown on xx.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        2 => array(
                            'key' => 'field_5f68be8c4b154',
                            'label' => 'Button text',
                            'name' => 'start_guide_title',
                            'type' => 'text',
                            'instructions' => 'Text for button that starts the interactive guide.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        3 => array(
                            'key' => 'field_5f68bf83a8256',
                            'label' => 'Image',
                            'name' => 'image',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'preview_size' => 'medium',
                            'library' => 'uploadedTo',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => 'png, jpeg, jpg, svg, gif',
                        ),
                    ),
                    'min' => '',
                    'max' => '1',
                ),
                'layout_5f68b3585a3fc' => array(
                    'key' => 'layout_5f68b3585a3fc',
                    'name' => 'chapter',
                    'label' => __('Chapter', 'event-manager'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_5f68b68e6239e',
                            'label' => 'Content',
                            'name' => 'text',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                'layout_5f68b70d623a2' => array(
                    'key' => 'layout_5f68b70d623a2',
                    'name' => 'text_message',
                    'label' => __('Text message', 'event-manager'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_5f68b717623a3',
                            'label' => 'Message',
                            'name' => 'text',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                'layout_5f68b7d8e8051' => array(
                    'key' => 'layout_5f68b7d8e8051',
                    'name' => 'image',
                    'label' => __('Image', 'event-manager'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_5f68b7f2e8052',
                            'label' => 'Upload image',
                            'name' => 'image',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'preview_size' => 'medium',
                            'library' => 'uploadedTo',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => 'png, jpeg, jpg, svg, gif',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                'layout_5f6999c722cbb' => array(
                    'key' => 'layout_5f6999c722cbb',
                    'name' => 'button',
                    'label' => __('Button', 'event-manager'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_5f6b3fa80750d',
                            'label' => '',
                            'name' => '',
                            'type' => 'message',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => 'Add one or many choice alternatives.',
                            'new_lines' => 'wpautop',
                            'esc_html' => 0,
                        ),
                        1 => array(
                            'key' => 'field_5f6999f122cbc',
                            'label' => '',
                            'name' => 'choices',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => '',
                            'min' => 1,
                            'max' => 0,
                            'layout' => 'block',
                            'button_label' => 'Add alternative',
                            'sub_fields' => array(
                                0 => array(
                                    'key' => 'field_5f699a0322cbd',
                                    'label' => 'Alternative',
                                    'name' => 'text',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                1 => array(
                                    'key' => 'field_5f699ac322cbe',
                                    'label' => 'Responses',
                                    'name' => 'responses',
                                    'type' => 'repeater',
                                    'instructions' => 'Response messages that is shown after this choice is selected.',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'collapsed' => '',
                                    'min' => 0,
                                    'max' => 0,
                                    'layout' => 'block',
                                    'button_label' => 'Add response',
                                    'sub_fields' => array(
                                        0 => array(
                                            'key' => 'field_5f699ae922cbf',
                                            'label' => 'Response',
                                            'name' => 'text',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 1,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'maxlength' => '',
                                        ),
                                    ),
                                ),
                            ),
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                'layout_5f699e205015c' => array(
                    'key' => 'layout_5f699e205015c',
                    'name' => 'dialog',
                    'label' => __('Dialog', 'event-manager'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_5f699f3150162',
                            'label' => 'Title',
                            'name' => 'title',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        1 => array(
                            'key' => 'field_5f699f3a50163',
                            'label' => 'Instructions',
                            'name' => 'instructions',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        2 => array(
                            'key' => 'field_5f699f4650164',
                            'label' => 'Message',
                            'name' => 'message',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        3 => array(
                            'key' => 'field_5f699e4a50161',
                            'label' => 'Icon',
                            'name' => 'icon',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'discuss' => 'Discuss',
                                'look' => 'Look',
                                'question' => 'Question',
                            ),
                            'default_value' => array(
                            ),
                            'allow_null' => 1,
                            'multiple' => 0,
                            'ui' => 0,
                            'return_format' => 'value',
                            'ajax' => 0,
                            'placeholder' => '',
                        ),
                        4 => array(
                            'key' => 'field_5f699e205015d',
                            'label' => '',
                            'name' => 'alternatives',
                            'type' => 'repeater',
                            'instructions' => 'Add one or many choice alternatives.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => '',
                            'min' => 1,
                            'max' => 0,
                            'layout' => 'block',
                            'button_label' => 'Add alternative',
                            'sub_fields' => array(
                                0 => array(
                                    'key' => 'field_5f699e205015e',
                                    'label' => 'Alternative',
                                    'name' => 'text',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                1 => array(
                                    'key' => 'field_5f69be5b2d957',
                                    'label' => 'Correct',
                                    'name' => 'correct',
                                    'type' => 'true_false',
                                    'instructions' => 'Set to no if the dialog shall repeat itself until a correct alternative is answered.',
                                    'required' => 0,
                                    'conditional_logic' => array(
                                        0 => array(
                                            0 => array(
                                                'field' => 'field_5f699e205015d',
                                                'operator' => '>',
                                                'value' => '1',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'message' => '',
                                    'default_value' => 1,
                                    'ui' => 1,
                                    'ui_on_text' => '',
                                    'ui_off_text' => '',
                                ),
                                2 => array(
                                    'key' => 'field_5f699e205015f',
                                    'label' => 'Responses',
                                    'name' => 'responses',
                                    'type' => 'repeater',
                                    'instructions' => 'Response messages that is shown after this choice is selected.',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'collapsed' => '',
                                    'min' => 0,
                                    'max' => 0,
                                    'layout' => 'block',
                                    'button_label' => 'Add response',
                                    'sub_fields' => array(
                                        0 => array(
                                            'key' => 'field_5f699e2050160',
                                            'label' => 'Response',
                                            'name' => 'text',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 1,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'maxlength' => '',
                                        ),
                                    ),
                                ),
                            ),
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                'layout_5f69fb94c188b' => array(
                    'key' => 'layout_5f69fb94c188b',
                    'name' => 'finish',
                    'label' => __('Finish', 'event-manager'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_5f6b033898f9d',
                            'label' => '',
                            'name' => '',
                            'type' => 'message',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => 'This is the last step for an interactive guide.',
                            'new_lines' => 'wpautop',
                            'esc_html' => 0,
                        ),
                        1 => array(
                            'key' => 'field_5f68a5c605ada',
                            'label' => 'Header title',
                            'name' => 'header_title',
                            'type' => 'text',
                            'instructions' => 'Title to be displayed on finish screen header.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        2 => array(
                            'key' => 'field_5f68aa923521c',
                            'label' => 'Content area title',
                            'name' => 'content_area_title',
                            'type' => 'text',
                            'instructions' => 'Title to be displayed in the content area.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        3 => array(
                            'key' => 'field_5f68aaa83521d',
                            'label' => 'Content area text',
                            'name' => 'content_area_text',
                            'type' => 'text',
                            'instructions' => 'Text to be displayed in the content area.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        4 => array(
                            'key' => 'field_5f68a63cd0fe4',
                            'label' => 'Images',
                            'name' => 'images',
                            'type' => 'repeater',
                            'instructions' => 'Images to be shown in content area.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => '',
                            'min' => 0,
                            'max' => 0,
                            'layout' => 'block',
                            'button_label' => 'Add image',
                            'sub_fields' => array(
                                0 => array(
                                    'key' => 'field_5f68a5d605adb',
                                    'label' => 'Image',
                                    'name' => 'image',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => array(
                                        0 => array(
                                            0 => array(
                                                'field' => 'field_5f68b2656239c',
                                                'operator' => '!=empty',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'array',
                                    'preview_size' => 'medium',
                                    'library' => 'uploadedTo',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => 'png, jpeg, jpg, svg, gif',
                                ),
                            ),
                        ),
                        5 => array(
                            'key' => 'field_5f6a0dfd6f6be',
                            'label' => 'Share result',
                            'name' => 'share_result',
                            'type' => 'group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'block',
                            'sub_fields' => array(
                                0 => array(
                                    'key' => 'field_5f68a6bb0ee01',
                                    'label' => 'Share title',
                                    'name' => 'share_title',
                                    'type' => 'text',
                                    'instructions' => 'Title to be shown on share button.',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                1 => array(
                                    'key' => 'field_5f68a6d00ee02',
                                    'label' => 'Share image',
                                    'name' => 'image',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'array',
                                    'preview_size' => 'medium',
                                    'library' => 'uploadedTo',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => 'png, jpeg, jpg, svg, gif',
                                ),
                            ),
                        ),
                    ),
                    'min' => '',
                    'max' => '1',
                ),
            ),
            'button_label' => __('Add step', 'event-manager'),
            'min' => 1,
            'max' => '',
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'interactive_guide',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));
}