<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_661e425070deb',
    'title' => __('Time &amp; Location', 'api-event-manager'),
    'fields' => array(
        0 => array(
            'key' => 'field_65a66d8cadeef',
            'label' => __('Occasions', 'api-event-manager'),
            'name' => 'occasions',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => __('When is the event scheduled to take place? You have the option to establish a recurring schedule or specify up to 10 distinct dates and times.', 'api-event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'pagination' => 0,
            'min' => 1,
            'max' => 10,
            'collapsed' => '',
            'button_label' => __('<span class="c-icon c-icon--material material-symbols-outlined material-symbols-outlined--filled c-icon--size-md" material-symbol="arrow_right_alt" role="img" aria-label="Icon: Undefined" alt="Icon: Repeat" data-nosnippet="" translate="no" aria-hidden="true">add</span> Add occation', 'api-event-manager'),
            'rows_per_page' => 20,
            'acfe_repeater_stylised_button' => 0,
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_65a681f9a99e9',
                    'label' => __('Date', 'api-event-manager'),
                    'name' => 'date',
                    'aria-label' => '',
                    'type' => 'date_picker',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'is_publicly_hidden' => 0,
                    'is_privately_hidden' => 0,
                    'display_format' => 'l j F Y',
                    'return_format' => 'Y-m-d',
                    'first_day' => 1,
                    'parent_repeater' => 'field_65a66d8cadeef',
                ),
                1 => array(
                    'key' => 'field_65a68507a99eb',
                    'label' => __('Start time', 'api-event-manager'),
                    'name' => 'startTime',
                    'aria-label' => '',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'is_publicly_hidden' => 0,
                    'is_privately_hidden' => 0,
                    'display_format' => 'H:i',
                    'return_format' => 'H:i',
                    'parent_repeater' => 'field_65a66d8cadeef',
                ),
                2 => array(
                    'key' => 'field_65a6852da99ec',
                    'label' => __('End time', 'api-event-manager'),
                    'name' => 'endTime',
                    'aria-label' => '',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'is_publicly_hidden' => 0,
                    'is_privately_hidden' => 0,
                    'display_format' => 'H:i',
                    'return_format' => 'H:i',
                    'parent_repeater' => 'field_65a66d8cadeef',
                ),
            ),
        ),
        1 => array(
            'key' => 'field_665089e28932a',
            'label' => __('Physical or virtual event?', 'api-event-manager'),
            'name' => 'physical_virtual',
            'aria-label' => '',
            'type' => 'button_group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 0,
            'choices' => array(
                'physical' => __('Physical', 'api-event-manager'),
                'virtual' => __('Virtual', 'api-event-manager'),
            ),
            'default_value' => __('physical', 'api-event-manager'),
            'return_format' => 'value',
            'allow_null' => 0,
            'layout' => 'horizontal',
        ),
        2 => array(
            'key' => 'field_665095ca3b9a4',
            'label' => __('Location name', 'api-event-manager'),
            'name' => 'location_name',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => __('You may set a name of this location, to better describe it.', 'api-event-manager'),
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_665089e28932a',
                        'operator' => '==',
                        'value' => 'physical',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 0,
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        3 => array(
            'key' => 'field_65a245c3a4062',
            'label' => __('Location', 'api-event-manager'),
            'name' => 'location',
            'aria-label' => '',
            'type' => 'open_street_map',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_665089e28932a',
                        'operator' => '==',
                        'value' => 'physical',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'center_lat' => 53.55064,
            'center_lng' => 10.00065,
            'zoom' => 12,
            'height' => 400,
            'return_format' => 'leaflet',
            'allow_map_layers' => 1,
            'max_markers' => 1,
            'layers' => array(
                0 => 'OpenStreetMap.Mapnik',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 0,
            'leaflet_map' => '{"lat":53.55064,"lng":10.00065,"zoom":12,"layers":["OpenStreetMap.Mapnik"],"markers":[]}',
        ),
        4 => array(
            'key' => 'field_66508a5b8932b',
            'label' => __('Meeting Link', 'api-event-manager'),
            'name' => 'meeting_link',
            'aria-label' => '',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_665089e28932a',
                        'operator' => '==',
                        'value' => 'virtual',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 0,
            'default_value' => '',
            'placeholder' => '',
        ),
        5 => array(
            'key' => 'field_665099c9a92cc',
            'label' => __('Travel information', 'api-event-manager'),
            'name' => 'travel',
            'aria-label' => '',
            'type' => 'textarea',
            'instructions' => __('Add information about how participants may get to your event.', 'api-event-manager'),
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_665089e28932a',
                        'operator' => '==',
                        'value' => 'physical',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 0,
            'default_value' => '',
            'acfe_textarea_code' => 0,
            'maxlength' => '',
            'allow_in_bindings' => 1,
            'rows' => 8,
            'placeholder' => '',
            'new_lines' => '',
        ),
        6 => array(
            'key' => 'field_66509a45a92cd',
            'label' => __('Connect information', 'api-event-manager'),
            'name' => 'connect',
            'aria-label' => '',
            'type' => 'textarea',
            'instructions' => __('Give your attendees information about how to connect to your meeting.', 'api-event-manager'),
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_665089e28932a',
                        'operator' => '==',
                        'value' => 'virtual',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 0,
            'default_value' => '',
            'acfe_textarea_code' => 0,
            'maxlength' => '',
            'rows' => '',
            'placeholder' => '',
            'new_lines' => '',
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'event',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => 'Give your guests the important details they need: when and where your event is happening.',
    'show_in_rest' => 1,
    'acfe_display_title' => '',
    'acfe_autosync' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
));
}