<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_57612f9baa78b',
    'title' => __('Location', 'event-manager'),
    'fields' => array(
        0 => array(
            'key' => 'field_57d26cffc2f68',
            'label' => __('Address', 'event-manager'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        1 => array(
            'key' => 'field_57612fb7d3ffc',
            'label' => __('Street address', 'event-manager'),
            'name' => 'street_address',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        2 => array(
            'key' => 'field_57612fc8d3ffd',
            'label' => __('Postal code', 'event-manager'),
            'name' => 'postal_code',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        3 => array(
            'key' => 'field_57612fd0d3ffe',
            'label' => __('City', 'event-manager'),
            'name' => 'city',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        4 => array(
            'key' => 'field_57612fefd3fff',
            'label' => __('Municipial', 'event-manager'),
            'name' => 'municipality',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        5 => array(
            'key' => 'field_57612fadd3ffb',
            'label' => __('Country', 'event-manager'),
            'name' => 'country',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        6 => array(
            'key' => 'field_5832ece755362',
            'label' => __('Map', 'event-manager'),
            'name' => 'geo_map',
            'type' => 'google_map',
            'instructions' => __('The map shows where the site is located and is not editable.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'center_lat' => 'null',
            'center_lng' => 'null',
            'zoom' => 16,
            'height' => '',
        ),
        7 => array(
            'key' => 'field_57cfba1b54b27',
            'label' => __('Open hours', 'event-manager'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        8 => array(
            'key' => 'field_58a2cba44c79c',
            'label' => __('Open hours', 'event-manager'),
            'name' => 'open_hours',
            'type' => 'repeater',
            'instructions' => __('Add open hours for this location.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'block',
            'button_label' => __('Lägg till', 'event-manager'),
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_58a2cbc24c79d',
                    'label' => __('Weekday', 'event-manager'),
                    'name' => 'weekday',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        1 => __('Monday', 'event-manager'),
                        2 => __('Tuesday', 'event-manager'),
                        3 => __('Wednesday', 'event-manager'),
                        4 => __('Thursday', 'event-manager'),
                        5 => __('Friday', 'event-manager'),
                        6 => __('Saturday', 'event-manager'),
                        7 => __('Sunday', 'event-manager'),
                    ),
                    'default_value' => array(
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                ),
                1 => array(
                    'key' => 'field_58a2cd794c79e',
                    'label' => __('Closed', 'event-manager'),
                    'name' => 'closed',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                ),
                2 => array(
                    'key' => 'field_58a2cd9e4c79f',
                    'label' => __('Opening', 'event-manager'),
                    'name' => 'opening',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_58a2cd794c79e',
                                'operator' => '!=',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i',
                    'return_format' => 'H:i',
                ),
                3 => array(
                    'key' => 'field_58a2cde54c7a0',
                    'label' => __('Closing', 'event-manager'),
                    'name' => 'closing',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_58a2cd794c79e',
                                'operator' => '!=',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i',
                    'return_format' => 'H:i',
                ),
            ),
        ),
        9 => array(
            'key' => 'field_57cfba70697e1',
            'label' => __('Undantag för öppettider', 'event-manager'),
            'name' => 'open_hour_exceptions',
            'type' => 'repeater',
            'instructions' => __('Lägg till ett eller flera undantag.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => __('Lägg till undantag', 'event-manager'),
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_57cfbb60697e2',
                    'label' => __('Date', 'event-manager'),
                    'name' => 'exception_date',
                    'type' => 'date_picker',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '30',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'Y-m-d',
                    'return_format' => 'Y-m-d',
                    'first_day' => 1,
                ),
                1 => array(
                    'key' => 'field_57cfbbb9697e3',
                    'label' => __('Exeption information', 'event-manager'),
                    'name' => 'exeption_information',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '70',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
            ),
        ),
        10 => array(
            'key' => 'field_57fca1e1dc2f0',
            'label' => __('Gallery', 'event-manager'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        11 => array(
            'key' => 'field_57fca1efdc2f1',
            'label' => __('Gallery', 'event-manager'),
            'name' => 'gallery',
            'type' => 'gallery',
            'instructions' => __('Add images to this location. Please upload images that are as large as possible and that are not sensitive to cropping (eg. images with text overlay).', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'min' => '',
            'max' => '',
            'insert' => 'append',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        12 => array(
            'key' => 'field_59426f53ca437',
            'label' => __('Social media', 'event-manager'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        13 => array(
            'key' => 'field_5942707eca439',
            'label' => __('Social media', 'event-manager'),
            'name' => 'links',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => '',
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_59427095ca43a',
                    'label' => __('Social media', 'event-manager'),
                    'name' => 'social_media',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'bambuser' => __('Bambuser', 'event-manager'),
                        'facebook' => __('Facebook', 'event-manager'),
                        'instagram' => __('Instagram', 'event-manager'),
                        'twitter' => __('Twitter', 'event-manager'),
                        'vimeo' => __('Vimeo', 'event-manager'),
                        'youtube' => __('Youtube', 'event-manager'),
                    ),
                    'default_value' => array(
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                ),
                1 => array(
                    'key' => 'field_5942725dca43b',
                    'label' => __('Url', 'event-manager'),
                    'name' => 'url',
                    'type' => 'url',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                ),
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'location',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));
}