<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_57c94757c2169',
    'title' => __('Package', 'event-manager'),
    'fields' => array(
        0 => array(
            'key' => 'field_5885b8a1f95bc',
            'label' => __('Package', 'event-manager'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        1 => array(
            'key' => 'field_57c94b88d8030',
            'label' => __('Events included', 'event-manager'),
            'name' => 'events_included',
            'type' => 'post_object',
            'instructions' => __('Select which events that are included in this package.', 'event-manager'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'post_type' => array(
                0 => 'event',
            ),
            'taxonomy' => array(
            ),
            'allow_null' => 0,
            'multiple' => 1,
            'return_format' => 'object',
            'ui' => 1,
        ),
        2 => array(
            'key' => 'field_57c949391d1b8',
            'label' => __('Booking link', 'event-manager'),
            'name' => 'booking_link',
            'type' => 'url',
            'instructions' => __('External link to booking website.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
        ),
        3 => array(
            'key' => 'field_57c949a4829ef',
            'label' => __('Booking phone', 'event-manager'),
            'name' => 'booking_phone',
            'type' => 'text',
            'instructions' => __('Phone number to make bookings.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        4 => array(
            'key' => 'field_57c949ad829f0',
            'label' => __('Minimum age to attend the event', 'event-manager'),
            'name' => 'age_restriction',
            'type' => 'number',
            'instructions' => __('Enter age if this event is age restricted.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => __('e.g. 15', 'event-manager'),
            'prepend' => '',
            'append' => __('year', 'event-manager'),
            'min' => 0,
            'max' => '',
            'step' => '',
        ),
        5 => array(
            'key' => 'field_581847f9642dc',
            'label' => __('Included in membership cards', 'event-manager'),
            'name' => 'membership_cards',
            'type' => 'post_object',
            'instructions' => __('Add membership cards where this package is included.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'post_type' => array(
                0 => 'membership-card',
            ),
            'taxonomy' => array(
            ),
            'allow_null' => 0,
            'multiple' => 1,
            'return_format' => 'object',
            'ui' => 1,
        ),
        6 => array(
            'key' => 'field_57c949bf829f3',
            'label' => __('Default price / Adult', 'event-manager'),
            'name' => 'price_adult',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => __('SEK', 'event-manager'),
            'maxlength' => '',
        ),
        7 => array(
            'key' => 'field_57c949c7829f5',
            'label' => __('Price student', 'event-manager'),
            'name' => 'price_student',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => __('SEK', 'event-manager'),
            'maxlength' => '',
        ),
        8 => array(
            'key' => 'field_57c949c3829f4',
            'label' => __('Price children', 'event-manager'),
            'name' => 'price_children',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => __('SEK', 'event-manager'),
            'maxlength' => '',
        ),
        9 => array(
            'key' => 'field_58184887642dd',
            'label' => __('Age restriction for children price', 'event-manager'),
            'name' => 'children_age',
            'type' => 'select',
            'instructions' => __('Children price is valid up to this age.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                0 => __('0', 'event-manager'),
                1 => __('1', 'event-manager'),
                2 => __('2', 'event-manager'),
                3 => __('3', 'event-manager'),
                4 => __('4', 'event-manager'),
                5 => __('5', 'event-manager'),
                6 => __('6', 'event-manager'),
                7 => __('7', 'event-manager'),
                8 => __('8', 'event-manager'),
                9 => __('9', 'event-manager'),
                10 => __('10', 'event-manager'),
                11 => __('11', 'event-manager'),
                12 => __('12', 'event-manager'),
                13 => __('13', 'event-manager'),
                14 => __('14', 'event-manager'),
                15 => __('15', 'event-manager'),
                16 => __('16', 'event-manager'),
                17 => __('17', 'event-manager'),
                18 => __('18', 'event-manager'),
                19 => __('19', 'event-manager'),
                20 => __('20', 'event-manager'),
                21 => __('21', 'event-manager'),
                22 => __('22', 'event-manager'),
                23 => __('23', 'event-manager'),
                24 => __('24', 'event-manager'),
                25 => __('25', 'event-manager'),
            ),
            'default_value' => array(
            ),
            'allow_null' => 1,
            'multiple' => 0,
            'ui' => 0,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '',
        ),
        10 => array(
            'key' => 'field_57c949cb829f6',
            'label' => __('Price senior', 'event-manager'),
            'name' => 'price_senior',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => __('SEK', 'event-manager'),
            'maxlength' => '',
        ),
        11 => array(
            'key' => 'field_58184909642de',
            'label' => __('Age restriction for senior price', 'event-manager'),
            'name' => 'senior_age',
            'type' => 'select',
            'instructions' => __('Senior price is valid from this age.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                50 => __('50', 'event-manager'),
                51 => __('51', 'event-manager'),
                52 => __('52', 'event-manager'),
                53 => __('53', 'event-manager'),
                54 => __('54', 'event-manager'),
                55 => __('55', 'event-manager'),
                56 => __('56', 'event-manager'),
                57 => __('57', 'event-manager'),
                58 => __('58', 'event-manager'),
                59 => __('59', 'event-manager'),
                60 => __('60', 'event-manager'),
                61 => __('61', 'event-manager'),
                62 => __('62', 'event-manager'),
                63 => __('63', 'event-manager'),
                64 => __('64', 'event-manager'),
                65 => __('65', 'event-manager'),
                66 => __('66', 'event-manager'),
                67 => __('67', 'event-manager'),
                68 => __('68', 'event-manager'),
                69 => __('69', 'event-manager'),
                70 => __('70', 'event-manager'),
                71 => __('71', 'event-manager'),
                72 => __('72', 'event-manager'),
                73 => __('73', 'event-manager'),
                74 => __('74', 'event-manager'),
                75 => __('75', 'event-manager'),
                76 => __('76', 'event-manager'),
                77 => __('77', 'event-manager'),
                78 => __('78', 'event-manager'),
                79 => __('79', 'event-manager'),
                80 => __('80', 'event-manager'),
                81 => __('81', 'event-manager'),
                82 => __('82', 'event-manager'),
                83 => __('83', 'event-manager'),
                84 => __('84', 'event-manager'),
                85 => __('85', 'event-manager'),
            ),
            'default_value' => array(
            ),
            'allow_null' => 1,
            'multiple' => 0,
            'ui' => 0,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '',
        ),
        12 => array(
            'key' => 'field_5818498849ea9',
            'label' => __('Price group', 'event-manager'),
            'name' => 'booking_group',
            'type' => 'repeater',
            'instructions' => __('Add prices for group bookings.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'block',
            'button_label' => __('Add group', 'event-manager'),
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_5818498949eaa',
                    'label' => __('Price group', 'event-manager'),
                    'name' => 'price_group',
                    'type' => 'text',
                    'instructions' => __('Price for this group.', 'event-manager'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => __('SEK', 'event-manager'),
                    'maxlength' => '',
                ),
                1 => array(
                    'key' => 'field_5818498949eab',
                    'label' => __('Min persons', 'event-manager'),
                    'name' => 'min_persons',
                    'type' => 'number',
                    'instructions' => __('Minimum number of people.', 'event-manager'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                2 => array(
                    'key' => 'field_5818498949eac',
                    'label' => __('Max persons', 'event-manager'),
                    'name' => 'max_persons',
                    'type' => 'number',
                    'instructions' => __('Maximum number of people.', 'event-manager'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
            ),
        ),
        13 => array(
            'key' => 'field_57c949b4829f1',
            'label' => __('Price information', 'event-manager'),
            'name' => 'price_information',
            'type' => 'textarea',
            'instructions' => __('Write additional information about prices.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 3,
            'new_lines' => 'wpautop',
        ),
        14 => array(
            'key' => 'field_57c949b9829f2',
            'label' => __('Ticket includes', 'event-manager'),
            'name' => 'ticket_includes',
            'type' => 'textarea',
            'instructions' => __('Does the ticket include more than entry? Then write what\'s included in one ticket.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => __('e.g. entry, checkroom, meal', 'event-manager'),
            'maxlength' => '',
            'rows' => 3,
            'new_lines' => 'wpautop',
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'package',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));
}