<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_5b15284158289',
    'title' => __('Recommendation', 'event-manager'),
    'fields' => array(
        0 => array(
            'key' => 'field_5b154867033d7',
            'label' => __('General', 'event-manager'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        1 => array(
            'key' => 'field_5b1528d04d135',
            'label' => __('Tagline', 'event-manager'),
            'name' => 'tagline',
            'type' => 'text',
            'instructions' => __('Short tagline that describes what this is about.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        2 => array(
            'key' => 'field_5b154c8575152',
            'label' => __('Location', 'event-manager'),
            'name' => 'location',
            'type' => 'post_object',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'post_type' => array(
                0 => 'location',
            ),
            'taxonomy' => array(
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'return_format' => 'id',
            'ui' => 1,
        ),
        3 => array(
            'key' => 'field_5b154c8b75157',
            'label' => __('For kids', 'event-manager'),
            'name' => 'child_friendly',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => __('This recommendation has target group "kids".', 'event-manager'),
            'default_value' => 0,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        4 => array(
            'key' => 'field_5b154d701904f',
            'label' => __('Links & Resources', 'event-manager'),
            'name' => 'links',
            'type' => 'repeater',
            'instructions' => __('Add links related to the recommendation. This can be a website or a published file (on the web) containing further information about the object.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => 'secondary-panel',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 20,
            'layout' => 'block',
            'button_label' => __('Add new link', 'event-manager'),
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_5b154d7019050',
                    'label' => __('Linkname', 'event-manager'),
                    'name' => 'link_title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                1 => array(
                    'key' => 'field_5b154d7019051',
                    'label' => __('Web adress', 'event-manager'),
                    'name' => 'link_url',
                    'type' => 'url',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                ),
            ),
        ),
        5 => array(
            'key' => 'field_5b154dbdfef17',
            'label' => __('Profile', 'event-manager'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        6 => array(
            'key' => 'field_5b154e6240e0c',
            'label' => __('Profile name', 'event-manager'),
            'name' => 'profile_name',
            'type' => 'text',
            'instructions' => __('Name and surname of the profile.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        7 => array(
            'key' => 'field_5b154eb140e0d',
            'label' => __('Profile quote', 'event-manager'),
            'name' => 'profile_quote',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        8 => array(
            'key' => 'field_5b154ec6124a3',
            'label' => __('Profile image', 'event-manager'),
            'name' => 'profile_image',
            'type' => 'image',
            'instructions' => __('Image of the profile in jpg or png format.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '100',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => 'jpg,jpeg,png',
        ),
        9 => array(
            'key' => 'field_5b1549e83b9dc',
            'label' => __('Media', 'event-manager'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        10 => array(
            'key' => 'field_5b154723649a4',
            'label' => __('Gallery', 'event-manager'),
            'name' => 'gallery',
            'type' => 'gallery',
            'instructions' => __('Multiple images in jpg or png format.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '100',
                'class' => '',
                'id' => '',
            ),
            'min' => '',
            'max' => 10,
            'insert' => 'append',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => 'jpg,jpeg,png',
        ),
        11 => array(
            'key' => 'field_5b154727649a5',
            'label' => __('Audio', 'event-manager'),
            'name' => 'audio',
            'type' => 'file',
            'instructions' => __('The file should be fairly compressed. Preferred format of the audio is AAC+ V2.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'uploadedTo',
            'min_size' => '',
            'max_size' => 50,
            'mime_types' => 'm4a,aac,mp3',
        ),
        12 => array(
            'key' => 'field_5b15472a649a6',
            'label' => __('Video', 'event-manager'),
            'name' => 'video',
            'type' => 'file',
            'instructions' => __('The file should be fairly compressed. Preferred container of the video is MP4.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'uploadedTo',
            'min_size' => '',
            'max_size' => 50,
            'mime_types' => 'mp4',
        ),
        13 => array(
            'key' => 'field_5b154d938160d',
            'label' => __('Beacon', 'event-manager'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
        ),
        14 => array(
            'key' => 'field_5b1554283fcf8',
            'label' => __('Beacon namespace', 'event-manager'),
            'name' => 'beacon_namespace',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        15 => array(
            'key' => 'field_5b15542f3fcf9',
            'label' => __('Beacon ID', 'event-manager'),
            'name' => 'beacon_id',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        16 => array(
            'key' => 'field_5b1554323fcfa',
            'label' => __('Beacon distance', 'event-manager'),
            'name' => 'beacon_distance',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 5,
            'placeholder' => '',
            'prepend' => '',
            'append' => __('meters', 'event-manager'),
            'min' => 1,
            'max' => 50,
            'step' => 1,
        ),
        17 => array(
            'key' => 'field_5b1554423fcfb',
            'label' => __('Beacon location', 'event-manager'),
            'name' => 'beacon_location',
            'type' => 'post_object',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'post_type' => array(
                0 => 'location',
            ),
            'taxonomy' => array(
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'return_format' => 'id',
            'ui' => 1,
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'recommendation',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));
}