<?php

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_625fc20c520eb',
		'title' => 'TIX',
		'fields' => array(
			array(
				'key' => 'field_626bde59f2a42',
				'label' => __('Daily import', 'event-manager'),
				'name' => 'tix_daily_cron',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => __('Enable daily automatic import from TIX', 'event-manager'),
				'default_value' => 1,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_625fc25fd7812',
				'label' => __('API link', 'event-manager'),
				'name' => 'tix_api_url',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_625fd1f72dad4',
				'label' => __('Event keys', 'event-manager'),
				'name' => 'tix_event_keys',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'block',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_625fd21d2dad5',
						'label' => __('Event key', 'event-manager'),
						'name' => 'tix_event_key',
						'type' => 'text',
						'instructions' => __('Add Tix ticket API Key', 'event-manager'),
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_6262696325ce8',
						'label' => __('Default user groups', 'event-manager'),
						'name' => 'tix_publishing_groups',
						'type' => 'taxonomy',
						'instructions' => __('Select the user groups that you want to set as default to imported posts.', 'event-manager'),
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'taxonomy' => 'user_groups',
						'field_type' => 'checkbox',
						'add_term' => 1,
						'save_terms' => 0,
						'load_terms' => 0,
						'return_format' => 'id',
						'multiple' => 0,
						'allow_null' => 0,
					),
					array(
						'key' => 'field_62736dee9ac1f',
						'label' => __('Exclude tags', 'event-manager'),
						'name' => 'tix_filter_tags',
						'type' => 'text',
						'instructions' => __('Enter the name of the tags that you want to exclude from the import. Separate with commas.', 'event-manager'),
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_6267b1a230c2f',
						'label' => __('Default city', 'event-manager'),
						'name' => 'tix_default_city',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_6267bac59ccf8',
						'label' => __('Group event occasions', 'event-manager'),
						'name' => 'tix_group_occasions',
						'type' => 'true_false',
						'instructions' => __('Group event occasions under one event', 'event-manager'),
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 1,
						'ui' => 1,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
				),
			),
			array(
				'key' => 'field_62626499674a6',
				'label' => __('Post status', 'event-manager'),
				'name' => 'tix_post_status',
				'type' => 'radio',
				'instructions' => __('Select status of imported events.', 'event-manager'),
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'draft' => __('Draft', 'event-manager'),
					'publish' => __('Published', 'event-manager'),
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'publish',
				'layout' => 'vertical',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-options',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	endif;
