<?php

namespace HbgEventImporter\Acf;

/**
 * Load local ACF field groups with PHP
 */

class AcfGuide
{
    public function __construct()
    {
        add_action('acf/init', array($this, 'addLocalFieldGroups'));
    }

    public function addLocalFieldGroups()
    {
        if (function_exists('acf_add_local_field_group')):

        acf_add_local_field_group(array(
            'key' => 'group_589497ca3741e',
            'title' => __('Basic Guide Settings', 'event-manager'),
            'fields' => array(
                array(
                    'placement' => 'left',
                    'endpoint' => 0,
                    'key' => 'field_58949857fc7b0',
                    'label' => __('General', 'event-manager'),
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'tabs' => 'all',
                    'toolbar' => 'basic',
                    'media_upload' => 0,
                    'default_value' => '',
                    'delay' => 0,
                    'key' => 'field_58949813a052c',
                    'label' => __('Beskrivning', 'event-manager'),
                    'name' => 'guide_description',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'placement' => 'left',
                    'endpoint' => 0,
                    'key' => 'field_5894987dfc7b1',
                    'label' => __('Media', 'event-manager'),
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'library' => 'all',
                    'min' => '',
                    'max' => 10,
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => 'jpg,jpeg,png',
                    'insert' => 'append',
                    'key' => 'field_589dc93cde2d7',
                    'label' => __('Guide images', 'event-manager'),
                    'name' => 'guide_images',
                    'type' => 'gallery',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => 'secondary-panel',
                        'id' => '',
                    ),
                ),
                array(
                    'placement' => 'top',
                    'endpoint' => 0,
                    'key' => 'field_5899a94bff0ec',
                    'label' => __('Content objects', 'event-manager'),
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'sub_fields' => array(
                        array(
                            'placement' => 'top',
                            'endpoint' => 0,
                            'key' => 'field_589db03e16e51',
                            'label' => __('General', 'event-manager'),
                            'name' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                        array(
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => __('The title of the object', 'event-manager'),
                            'prepend' => '',
                            'append' => '',
                            'key' => 'field_5899aab938d3d',
                            'label' => __('Object title', 'event-manager'),
                            'name' => 'guide_object_title',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '75',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                        array(
                            'default_value' => '',
                            'maxlength' => 8,
                            'placeholder' => __('eg. object 205', 'event-manager'),
                            'prepend' => '#',
                            'append' => '',
                            'key' => 'field_589dcc1a7deb3',
                            'label' => __('Exhibition ID', 'event-manager'),
                            'name' => 'guide_object_id',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '25',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                        array(
                            'tabs' => 'all',
                            'toolbar' => 'basic',
                            'media_upload' => 1,
                            'default_value' => '',
                            'delay' => 0,
                            'key' => 'field_5899aae338d3e',
                            'label' => __('Object description', 'event-manager'),
                            'name' => 'guide_object_description',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                        array(
                            'placement' => 'top',
                            'endpoint' => 0,
                            'key' => 'field_589db05816e52',
                            'label' => __('Media', 'event-manager'),
                            'name' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                        array(
                            'library' => 'all',
                            'min' => '',
                            'max' => 10,
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => 'jpg,jpeg,png',
                            'insert' => 'append',
                            'key' => 'field_5899ab0338d3f',
                            'label' => __('Object image', 'event-manager'),
                            'name' => 'guide_object_image',
                            'type' => 'gallery',
                            'instructions' => __('Multiple images in jpg or png format of the object.', 'event-manager'),
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '100',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                        array(
                            'return_format' => 'array',
                            'library' => 'uploadedTo',
                            'min_size' => '',
                            'max_size' => 50,
                            'mime_types' => 'm4a,aac,mp3',
                            'key' => 'field_5899ab2c38d40',
                            'label' => __('Object audio', 'event-manager'),
                            'name' => 'guide_object_audio',
                            'type' => 'file',
                            'instructions' => __('An audiofile describing the object. This should be fairly compressed. Preferred format of the audio is AAC+ V2.', 'event-manager'),
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                        array(
                            'return_format' => 'array',
                            'library' => 'uploadedTo',
                            'min_size' => '',
                            'max_size' => 50,
                            'mime_types' => 'mp4',
                            'key' => 'field_5899ac03acc12',
                            'label' => __('Object video', 'event-manager'),
                            'name' => 'guide_object_video',
                            'type' => 'file',
                            'instructions' => __('An videofile describing the object. This should be fairly compressed. Preferred container of the video is MP4.', 'event-manager'),
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                        array(
                            'placement' => 'top',
                            'endpoint' => 0,
                            'key' => 'field_589db08d16e53',
                            'label' => __('Länkar', 'event-manager'),
                            'name' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                        array(
                            'sub_fields' => array(
                                array(
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'key' => 'field_5899e5e1a583d',
                                    'label' => __('Linkname', 'event-manager'),
                                    'name' => 'guide_object_link_title',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '50',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                ),
                                array(
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'key' => 'field_5899e64fa583e',
                                    'label' => __('Web adress', 'event-manager'),
                                    'name' => 'guide_object_link_url',
                                    'type' => 'url',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '50',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                ),
                            ),
                            'min' => 0,
                            'max' => 20,
                            'layout' => 'block',
                            'button_label' => __(__('Add new link', 'event-manager'), 'event-manager'),
                            'collapsed' => 'field_5899e5e1a583d',
                            'key' => 'field_5899e5c8a583c',
                            'label' => __('Links & Resources', 'event-manager'),
                            'name' => 'guide_object_links',
                            'type' => 'repeater',
                            'instructions' => __('Add links related to the object. This can be a website or a published file (on the web) containing further information about the object.', 'event-manager'),
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => 'secondary-panel',
                                'id' => '',
                            ),
                        ),
                        array(
                            'placement' => 'top',
                            'endpoint' => 0,
                            'key' => 'field_589db114078de',
                            'label' => __('Beacons', 'event-manager'),
                            'name' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'field_58949a8f0c4cd',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                        array(
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'key' => 'field_589db29081803',
                            'label' => __('Object beacon ID', 'event-manager'),
                            'name' => 'guide_object_beacon_id',
                            'type' => 'text',
                            'instructions' => __('A unique id for a specific    bluetooth beacon.', 'event-manager'),
                            'required' => 1,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'field_58949a8f0c4cd',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '60',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                        array(
                            'default_value' => 5,
                            'min' => 1,
                            'max' => 70,
                            'step' => 1,
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => __('meters', 'event-manager'),
                            'key' => 'field_589dc6da3611c',
                            'label' => __('Beacon trigger distance', 'event-manager'),
                            'name' => 'guide_object_beacon_distance',
                            'type' => 'number',
                            'instructions' => __('Distance that the beacon should be triggered at.', 'event-manager'),
                            'required' => 1,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'field_58949a8f0c4cd',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '40',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                        array(
                            'placement' => 'top',
                            'endpoint' => 0,
                            'key' => 'field_58a5c081f4193',
                            'label' => __('Visibility', 'event-manager'),
                            'name' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                        array(
                            'default_value' => 0,
                            'message' => __('Yes, show this object', 'event-manager'),
                            'ui' => 0,
                            'ui_on_text' => __('Show', 'event-manager'),
                            'ui_off_text' => __('Hide', 'event-manager'),
                            'key' => 'field_58a5c098f4194',
                            'label' => __('Object visibility', 'event-manager'),
                            'name' => 'guide_object_active',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                        array(
                            'key' => 'field_58ad84a12d5ac',
                            'label' => __('Unique ID', 'event-manager'),
                            'name' => 'guide_object_uid',
                            'type' => 'unique_id',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                    ),
                    'min' => 1,
                    'max' => 500,
                    'layout' => 'block',
                    'button_label' => __(__('Add new object', 'event-manager'), 'event-manager'),
                    'collapsed' => 'field_5899aab938d3d',
                    'key' => 'field_5899cc4b59d94',
                    'label' => __('Content (paintings, art, flowers etc.)', 'event-manager'),
                    'name' => 'guide_content_objects',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'placement' => 'top',
                    'endpoint' => 0,
                    'key' => 'field_58ab0c6354b09',
                    'label' => __('Beacons', 'event-manager'),
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'key' => 'field_58ac5c65cdffe',
                    'label' => __('Beacon namespace', 'event-manager'),
                    'name' => 'guide_beacon_namespace',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'sub_fields' => array(
                        array(
                            'post_type' => array(
                                0 => 'location',
                            ),
                            'taxonomy' => array(
                            ),
                            'allow_null' => 0,
                            'multiple' => 0,
                            'return_format' => 'id',
                            'ui' => 1,
                            'key' => 'field_58ab0c9554b0a',
                            'label' => __('Plats', 'event-manager'),
                            'name' => 'location',
                            'type' => 'post_object',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '36',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                        array(
                            'multiple' => 1,
                            'allow_null' => 0,
                            'choices' => array(
                            ),
                            'default_value' => array(
                            ),
                            'ui' => 1,
                            'ajax' => 0,
                            'placeholder' => '',
                            'return_format' => 'value',
                            'key' => 'field_58ab0cf054b0b',
                            'label' => __('Objects', 'event-manager'),
                            'name' => 'objects',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '30',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                        array(
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'key' => 'field_58ac54a64bb06',
                            'label' => __('Beacon ID', 'event-manager'),
                            'name' => 'beacon',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '30',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                    ),
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'table',
                    'button_label' => __(__('Lägg till grupp', 'event-manager'), 'event-manager'),
                    'collapsed' => 'field_58ab0cf054b0b',
                    'key' => 'field_58ab0b4454b08',
                    'label' => __('Beacon groups', 'event-manager'),
                    'name' => 'guide_beacon',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'guide',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'field',
            'hide_on_screen' => '',
            'active' => 1,
            'description' => 'Manage main guide object details.',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_589dd0fbd412e',
            'title' => __('Guide Group', 'event-manager'),
            'fields' => array(
                array(
                    'taxonomy' => 'guidegroup',
                    'field_type' => 'select',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'return_format' => 'object',
                    'add_term' => 1,
                    'load_terms' => 0,
                    'save_terms' => 0,
                    'key' => 'field_589dd138aca7e',
                    'label' => __('Select the group for this guide', 'event-manager'),
                    'name' => 'guide_group',
                    'type' => 'taxonomy',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'guide',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'side',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => 1,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_589dcf7e047a8',
            'title' => __('Guide group settings', 'event-manager'),
            'fields' => array(
                array(
                    'default_value' => 1,
                    'message' => __('Yes, this group is active (show as clickable location i app).', 'event-manager'),
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                    'key' => 'field_58ac3daed44c3',
                    'label' => __('Active', 'event-manager'),
                    'name' => 'guide_taxonomy_active',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'library' => 'uploadedTo',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => 'svg, png',
                    'key' => 'field_589dcf9661090',
                    'label' => __('Logotype', 'event-manager'),
                    'name' => 'guide_taxonomy_logotype',
                    'type' => 'image',
                    'instructions' => __('A logotype that may be shown related to the guides with this category.', 'event-manager'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'default_value' => '#FFFFFF',
                    'key' => 'field_589dd18acd51f',
                    'label' => __('Color', 'event-manager'),
                    'name' => 'guide_taxonomy_color',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => 'colorpicker',
                        'id' => '',
                    ),
                ),
                array(
                    'return_format' => 'array',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => 'png, jpg, jpeg',
                    'key' => 'field_58a2d24ca466c',
                    'label' => __('Mood image', 'event-manager'),
                    'name' => 'guide_taxonomy_image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'post_type' => array(
                        0 => 'location',
                    ),
                    'taxonomy' => array(
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'return_format' => 'id',
                    'ui' => 1,
                    'key' => 'field_58ac3ca740387',
                    'label' => __('Plats', 'event-manager'),
                    'name' => 'guide_taxonomy_location',
                    'type' => 'post_object',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'default_value' => 50,
                    'min' => 50,
                    'max' => 10000,
                    'step' => 50,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => __('meters', 'event-manager'),
                    'key' => 'field_58b4091bc9dbf',
                    'label' => __('Location radius', 'event-manager'),
                    'name' => 'guide_taxonomy_radius',
                    'type' => 'number',
                    'instructions' => __('Trigger this location a the radius of n meters.', 'event-manager'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'default_value' => 0,
                    'message' => __('Yes, only allow the user to select from avabile sublications', 'event-manager'),
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                    'key' => 'field_58ad7751e92af',
                    'label' => __('Only allow sublocations', 'event-manager'),
                    'name' => 'guide_taxonomy_sublocations',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'default_value' => 1,
                    'message' => __('Yes, this location has full wifi coverage', 'event-manager'),
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                    'key' => 'field_58ac5da5ed8ff',
                    'label' => __('Wifi coverage', 'event-manager'),
                    'name' => 'guide_taxonomy_wifi',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'default_value' => 1,
                    'message' => __('Yes, this location may use google maps.', 'event-manager'),
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                    'key' => 'field_58ac5dc8ed900',
                    'label' => __('Karta', 'event-manager'),
                    'name' => 'guide_taxonomy_map',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'taxonomy',
                        'operator' => '==',
                        'value' => 'guidegroup',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => 1,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_58ab055a4b3b8',
            'title' => __('Notices', 'event-manager'),
            'fields' => array(
                array(
                    'sub_fields' => array(
                        array(
                            'default_value' => '',
                            'new_lines' => '',
                            'maxlength' => '',
                            'placeholder' => __('What do you want to say?', 'event-manager'),
                            'rows' => 4,
                            'key' => 'field_58ab0585c586f',
                            'label' => __('Message', 'event-manager'),
                            'name' => 'message',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                        array(
                            'default_value' => 5,
                            'min' => '',
                            'max' => '',
                            'step' => 1,
                            'placeholder' => '',
                            'prepend' => 'Delay',
                            'append' => __('minute(s)', 'event-manager'),
                            'key' => 'field_58ab05cac5870',
                            'label' => __('Timeout', 'event-manager'),
                            'name' => 'timeout',
                            'type' => 'number',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                    ),
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'table',
                    'button_label' => __(__('Add notice', 'event-manager'), 'event-manager'),
                    'collapsed' => 'field_58ab0585c586f',
                    'key' => 'field_58ab055ec586e',
                    'label' => __('Arrival notice', 'event-manager'),
                    'name' => 'guide_arrival_notice',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'sub_fields' => array(
                        array(
                            'default_value' => '',
                            'new_lines' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'rows' => 4,
                            'key' => 'field_58ab06528a9b1',
                            'label' => __('Message', 'event-manager'),
                            'name' => 'message',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                        array(
                            'default_value' => 10,
                            'min' => 0,
                            'max' => '',
                            'step' => 1,
                            'placeholder' => '',
                            'prepend' => 'Delay',
                            'append' => __('minute(s)', 'event-manager'),
                            'key' => 'field_58ab06698a9b2',
                            'label' => __('Timeout', 'event-manager'),
                            'name' => 'timeout',
                            'type' => 'number',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                    ),
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'table',
                    'button_label' => __(__('Add notice', 'event-manager'), 'event-manager'),
                    'collapsed' => '',
                    'key' => 'field_58ab063f8a9b0',
                    'label' => __('Departure notice', 'event-manager'),
                    'name' => 'guide_departure_notice',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'taxonomy',
                        'operator' => '==',
                        'value' => 'guidegroup',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => 1,
            'description' => '',
        ));

        endif;
    }
}
