<?php
if (function_exists('acf_add_local_field_group')):

acf_add_local_field_group(array(
    'key' => 'group_589497ca3741e',
    'title' => __('Basic Guide Settings', 'event-manager'),
    'fields' => array(
        array(
            'placement' => 'left',
            'endpoint' => 0,
            'key' => 'field_58949857fc7b0',
            'label' => __('General', 'event-manager'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
        array(
            'tabs' => 'all',
            'toolbar' => 'basic',
            'media_upload' => 0,
            'default_value' => '',
            'delay' => 0,
            'key' => 'field_58949813a052c',
            'label' => __('Description', 'event-manager'),
            'name' => 'guide_main_description',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
        array(
            'post_type' => array(
                0 => 'location',
            ),
            'taxonomy' => array(
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'return_format' => 'id',
            'ui' => 1,
            'key' => 'field_589498b7fc7b3',
            'label' => __('Plats', 'event-manager'),
            'name' => 'guide_main_location',
            'type' => 'post_object',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
        array(
            'placement' => 'left',
            'endpoint' => 0,
            'key' => 'field_5894987dfc7b1',
            'label' => __('Media', 'event-manager'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
        array(
            'library' => 'all',
            'min' => '',
            'max' => 10,
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => 'jpg,jpeg,png',
            'insert' => 'append',
            'key' => 'field_589dc93cde2d7',
            'label' => __('Guide images', 'event-manager'),
            'name' => 'guide_main_media',
            'type' => 'gallery',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => 'secondary-panel',
                'id' => '',
            ),
        ),
        array(
            'placement' => 'left',
            'endpoint' => 0,
            'key' => 'field_5894988bfc7b2',
            'label' => __('Beacon', 'event-manager'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
        array(
            'default_value' => 0,
            'message' => '',
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'key' => 'field_58949a8f0c4cd',
            'label' => __('Use beacons (bluetooth transmitters)', 'event-manager'),
            'name' => 'guide_main_use_beacon',
            'type' => 'true_false',
            'instructions' => __('Enable beacons to pinpoint the users location. If disabled the guide will rely on the users GPS position.', 'event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
        array(
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'key' => 'field_5898317b30d55',
            'label' => __('Beacon namespace identification', 'event-manager'),
            'name' => 'guide_main_beacon_namespace',
            'type' => 'text',
            'instructions' => __('A (common) namespace id representing the whole guide area. All beacons in the guid <u>must</u> use this id as their primary id.', 'event-manager'),
            'required' => 1,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_58949a8f0c4cd',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '100',
                'class' => '',
                'id' => '',
            ),
        ),
        array(
            'default_value' => 5,
            'min' => 1,
            'max' => 70,
            'step' => 1,
            'placeholder' => '',
            'prepend' => '',
            'append' => __('meters', 'event-manager'),
            'key' => 'field_589499e9609dd',
            'label' => __('Beacon trigger distance', 'event-manager'),
            'name' => 'guide_main_beacon_distance',
            'type' => 'number',
            'instructions' => __('Max distance 70 meters. More than 50 meters may not be reliable.', 'event-manager'),
            'required' => 1,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_58949a8f0c4cd',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '100',
                'class' => '',
                'id' => '',
            ),
        ),
        array(
            'placement' => 'top',
            'endpoint' => 0,
            'key' => 'field_5899a94bff0ec',
            'label' => __('Objects', 'event-manager'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
        array(
            'sub_fields' => array(
                array(
                    'placement' => 'top',
                    'endpoint' => 0,
                    'key' => 'field_589db03e16e51',
                    'label' => __('General', 'event-manager'),
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => __('The title of the object', 'event-manager'),
                    'prepend' => '',
                    'append' => '',
                    'key' => 'field_5899aab938d3d',
                    'label' => __('Object title', 'event-manager'),
                    'name' => 'guide_object_title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '75',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'default_value' => '',
                    'maxlength' => 8,
                    'placeholder' => __('eg. object 205', 'event-manager'),
                    'prepend' => '#',
                    'append' => '',
                    'key' => 'field_589dcc1a7deb3',
                    'label' => __('Exhibition ID', 'event-manager'),
                    'name' => 'guide_object_id',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'tabs' => 'all',
                    'toolbar' => 'basic',
                    'media_upload' => 1,
                    'default_value' => '',
                    'delay' => 0,
                    'key' => 'field_5899aae338d3e',
                    'label' => __('Object description', 'event-manager'),
                    'name' => 'guide_object_description',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'placement' => 'top',
                    'endpoint' => 0,
                    'key' => 'field_589db05816e52',
                    'label' => __('Media', 'event-manager'),
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'return_format' => 'array',
                    'preview_size' => 'thumbnail',
                    'library' => 'uploadedTo',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => 'jpg,jpeg,png',
                    'key' => 'field_5899ab0338d3f',
                    'label' => __('Object image', 'event-manager'),
                    'name' => 'guide_object_image',
                    'type' => 'image',
                    'instructions' => __('A single image in jpg or png format of the object.', 'event-manager'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33,333',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'return_format' => 'array',
                    'library' => 'uploadedTo',
                    'min_size' => '',
                    'max_size' => 50,
                    'mime_types' => 'm4a,aac,mp3',
                    'key' => 'field_5899ab2c38d40',
                    'label' => __('Object audio', 'event-manager'),
                    'name' => 'guide_object_audio',
                    'type' => 'file',
                    'instructions' => __('An audiofile describing the object. This should be fairly compressed. Preferred format of the audio is AAC+ V2.', 'event-manager'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33,333',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'return_format' => 'array',
                    'library' => 'uploadedTo',
                    'min_size' => '',
                    'max_size' => 50,
                    'mime_types' => 'mp4',
                    'key' => 'field_5899ac03acc12',
                    'label' => __('Object video', 'event-manager'),
                    'name' => 'guide_object_video',
                    'type' => 'file',
                    'instructions' => __('An videofile describing the object. This should be fairly compressed. Preferred container of the video is MP4.', 'event-manager'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33,333',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'placement' => 'top',
                    'endpoint' => 0,
                    'key' => 'field_589db08d16e53',
                    'label' => __('Länkar', 'event-manager'),
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'sub_fields' => array(
                        array(
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'key' => 'field_5899e5e1a583d',
                            'label' => __('Linkname', 'event-manager'),
                            'name' => 'guide_object_link_title',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                        array(
                            'default_value' => '',
                            'placeholder' => '',
                            'key' => 'field_5899e64fa583e',
                            'label' => __('Web adress', 'event-manager'),
                            'name' => 'guide_object_link_url',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                    ),
                    'min' => 0,
                    'max' => 20,
                    'layout' => 'block',
                    'button_label' => __(__('Add new link', 'event-manager'), 'event-manager'),
                    'collapsed' => 'field_5899e5e1a583d',
                    'key' => 'field_5899e5c8a583c',
                    'label' => __('Links & Resources', 'event-manager'),
                    'name' => 'guide_object_links',
                    'type' => 'repeater',
                    'instructions' => __('Add links related to the object. This can be a website or a published file (on the web) containing further information about the object.', 'event-manager'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => 'secondary-panel',
                        'id' => '',
                    ),
                ),
                array(
                    'placement' => 'top',
                    'endpoint' => 0,
                    'key' => 'field_589db114078de',
                    'label' => __('Beacons', 'event-manager'),
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_58949a8f0c4cd',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'key' => 'field_589db29081803',
                    'label' => __('Object beacon ID', 'event-manager'),
                    'name' => 'guide_object_beacon_id',
                    'type' => 'text',
                    'instructions' => __('A unique id for a specific    bluetooth beacon.', 'event-manager'),
                    'required' => 1,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_58949a8f0c4cd',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'default_value' => 5,
                    'min' => 1,
                    'max' => 70,
                    'step' => 1,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => __('meters', 'event-manager'),
                    'key' => 'field_589dc6da3611c',
                    'label' => __('Beacon trigger distance', 'event-manager'),
                    'name' => 'guide_object_beacon_distance',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_58949a8f0c4cd',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'placement' => 'top',
                    'endpoint' => 0,
                    'key' => 'field_589dc80299fb5',
                    'label' => __('Plats', 'event-manager'),
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'post_type' => array(
                        0 => 'location',
                    ),
                    'taxonomy' => array(
                    ),
                    'allow_null' => 1,
                    'multiple' => 0,
                    'return_format' => 'id',
                    'ui' => 1,
                    'key' => 'field_589dc81699fb6',
                    'label' => __('Plats', 'event-manager'),
                    'name' => 'guide_object_location',
                    'type' => 'post_object',
                    'instructions' => __('Choose a location that is related to this object. All sub-locations to a main location is avilabile here.', 'event-manager'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
            ),
            'min' => 1,
            'max' => 500,
            'layout' => 'block',
            'button_label' => __(__('Add new object', 'event-manager'), 'event-manager'),
            'collapsed' => 'field_5899aab938d3d',
            'key' => 'field_5899cc4b59d94',
            'label' => __('Objects (trigger places related to location or beacon)', 'event-manager'),
            'name' => 'guide_location_objects',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'guide',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'field',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => 'Manage main guide object details.',
));

endif;
